import {useState, type ReactNode} from 'react';
import {Card,CardHeader,Input,EmptyState} from './layout';
import {Button} from '../components/ui/button';
import {AppSelect} from '../components/ui/app-select';
import {DataTable,DataRow} from '../components/ui/data-table';
import './analytics.css';
export function PageLayout({title,description,action,children}:{title:string;description?:string;action?:ReactNode;children:ReactNode}){return <div className="bm-page"><header className="bm-page-heading"><div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</header><div className="bm-stack">{children}</div></div>}
export function Grid({children,columns=2,ratio}:{children:ReactNode;columns?:number;ratio?:"2:1"|"1:2"|"1:1"}){return <div className="bm-grid" data-ratio={ratio} style={{'--columns':columns} as React.CSSProperties}>{children}</div>}
export function Stack({children}:{children:ReactNode}){return <div className="bm-stack">{children}</div>}
export function SelectField({label,value,options,onChange,labels={}}:{label:string;value:string;options:string[];onChange:(value:string)=>void;labels?:Record<string,string>}){return <div className="bm-field"><span>{label}</span><AppSelect value={value} onValueChange={onChange} aria-label={label}>{options.map(option=><option key={option} value={option}>{labels[option]??option}</option>)}</AppSelect></div>}
export function KeyValueList({items}:{items:{label:string;value:ReactNode}[]}){return <dl className="bm-key-values">{items.map(item=><div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>}
export function Notice({children,error=false}:{children:ReactNode;error?:boolean}){return <p className="bm-notice" role={error?'alert':'status'} data-error={error}>{children}</p>}
export function ChoiceCards({items,onSelect}:{items:{id:string;title:string;description?:string}[];onSelect:(id:string)=>void}){return <Grid>{items.map(item=><Button key={item.id} className="bm-choice-card" onClick={()=>onSelect(item.id)}><strong>{item.title}</strong>{item.description&&<span>{item.description}</span>}</Button>)}</Grid>}
export function Pagination({page,totalPages,onChange,label='Page'}:{page:number;totalPages:number;onChange:(page:number)=>void;label?:string}){return <div className="bm-row"><Button aria-label="Previous page" disabled={page<=1} onClick={()=>onChange(page-1)}>←</Button><span>{label} {page} / {Math.max(1,totalPages)}</span><Button aria-label="Next page" disabled={page>=totalPages} onClick={()=>onChange(page+1)}>→</Button></div>}
export type ChartRow={id:string;label:string;values:number[];detail?:string};
export function BarChart({rows,series,unit='',selected,onSelect}:{rows:ChartRow[];series:string[];unit?:string;selected?:string;onSelect?:(id:string)=>void}){
 const max=Math.max(1,...rows.flatMap(r=>r.values.map(Math.abs)));const [active,setActive]=useState<string|null>(null);
 return <div className="bm-bar-chart"><div className="bm-chart-legend">{series.map((s,i)=><span key={s}><i data-series={i}/>{s}</span>)}</div>{rows.map(row=><div className="bm-chart-row" key={row.id} data-selected={selected===row.id}><Button variant="ghost" disabled={!onSelect} onClick={()=>onSelect?.(row.id)}>{row.label}</Button><div className="bm-chart-bars">{row.values.map((value,i)=><div key={i} className="bm-chart-track"><div className="bm-chart-bar" data-series={i} data-active={active===row.id+':'+i} tabIndex={0} role="img" aria-label={`${row.label}, ${series[i]}: ${value}${unit}`} onMouseEnter={()=>setActive(row.id+':'+i)} onMouseLeave={()=>setActive(null)} onFocus={()=>setActive(row.id+':'+i)} onBlur={()=>setActive(null)} style={{width:`${Math.abs(value)/max*100}%`}}/><span>{value.toLocaleString('en-CA',{maximumFractionDigits:1})}{unit}</span></div>)}</div>{row.detail&&<small>{row.detail}</small>}</div>)}</div>
}
export function RangeChart({rows,unit='',onSelect,selected}:{rows:{id:string;label:string;low:number;median:number;high:number;detail?:string}[];unit?:string;onSelect?:(id:string)=>void;selected?:string}){const min=Math.min(0,...rows.map(r=>r.low));const max=Math.max(1,...rows.map(r=>r.high));const pos=(v:number)=>(v-min)/(max-min)*100;return <div className="bm-range-chart">{rows.map(row=><div className="bm-chart-row" key={row.id} data-selected={selected===row.id}><Button variant="ghost" disabled={!onSelect} onClick={()=>onSelect?.(row.id)}>{row.label}</Button><div className="bm-range-track" role="img" tabIndex={0} aria-label={`${row.label}: ${row.low}${unit} to ${row.high}${unit}, median ${row.median}${unit}`}><i style={{left:`${pos(row.low)}%`,width:`${pos(row.high)-pos(row.low)}%`}}/><b style={{left:`${pos(row.median)}%`}}/></div><span>{row.median.toFixed(1)}{unit}</span><small>{row.detail??`${row.low.toFixed(1)}–${row.high.toFixed(1)}${unit}`}</small></div>)}</div>}
export function EvidenceMatrix({columns,rows}:{columns:string[];rows:{id:string;label:string;cells:{label:string;tone?:'positive'|'warning'|'muted'}[]}[]}){return <DataTable locale="en"><thead><tr><th>Item</th>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(row=><DataRow key={row.id}><td>{row.label}</td>{row.cells.map((cell,i)=><td key={i}><span className="bm-matrix-cell" data-tone={cell.tone}>{cell.label}</span></td>)}</DataRow>)}</tbody></DataTable>}
export type NetworkNode={id:string;label:string;kind:string;description?:string;metric?:string};
export function NetworkExplorer({nodes,links}:{nodes:NetworkNode[];links:{source:string;target:string;relation:string}[]}){
 const [query,setQuery]=useState('');const [kind,setKind]=useState('All types');const [id,setId]=useState([...nodes].sort((a,b)=>links.filter(l=>l.source===b.id||l.target===b.id).length-links.filter(l=>l.source===a.id||l.target===a.id).length)[0]?.id);const selected=nodes.find(n=>n.id===id);const matches=nodes.filter(n=>(kind==='All types'||n.kind===kind)&&`${n.label} ${n.description??''}`.toLowerCase().includes(query.toLowerCase()));const neighbors=links.filter(l=>l.source===id||l.target===id).map(l=>({link:l,node:nodes.find(n=>n.id===(l.source===id?l.target:l.source))})).filter(n=>n.node);
 const graphNodes=[...new Map(neighbors.map(n=>[n.node!.id,n.node!])).values()].slice(0,12);const positions=graphNodes.map((node,i)=>({node,x:320+230*Math.cos(i/graphNodes.length*Math.PI*2),y:180+120*Math.sin(i/graphNodes.length*Math.PI*2)}));
 return <div className="bm-network-explorer"><div className="bm-network-browser"><Grid><Input aria-label="Search network" placeholder="Search entities…" value={query} onChange={e=>setQuery(e.target.value)}/><AppSelect aria-label="Entity type" value={kind} onValueChange={setKind}>{['All types',...new Set(nodes.map(n=>n.kind))].map(k=><option key={k}>{k}</option>)}</AppSelect></Grid><Notice>{nodes.length} entities · {links.length} relationships · {matches.length} matches</Notice><div className="bm-network-list">{matches.map(n=><Button key={n.id} variant={n.id===id?'primary':'ghost'} onClick={()=>setId(n.id)}>{n.label}</Button>)}{!matches.length&&<EmptyState title="No matching entity" description="Try another search or entity type."/>}</div></div><div className="bm-network-inspector"><svg className="bm-network-map" viewBox="0 0 640 360" role="group" aria-label="Selected entity relationships">{positions.map(({node,x,y})=><line key={node.id} x1={320} y1={180} x2={x} y2={y}/>)}<g><circle cx={320} cy={180} r={22}/><text x={320} y={220} textAnchor="middle">{selected?.label}</text></g>{positions.map(({node,x,y})=><g key={node.id} role="button" tabIndex={0} aria-label={`Explore ${node.label}`} onClick={()=>setId(node.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setId(node.id)}}}><circle cx={x} cy={y} r={9}/><text x={x} y={y+24} textAnchor="middle">{node.label.length>24?node.label.slice(0,22)+'…':node.label}</text></g>)}</svg><Card><CardHeader title={selected?.label??'Select an entity'} description={selected?.description}/><KeyValueList items={[{label:'Type',value:selected?.kind},...(selected?.metric?[{label:'Signal',value:selected.metric}]:[])]}/><div className="bm-network-links">{neighbors.map(({node,link},i)=><Button key={i} onClick={()=>setId(node!.id)}><small>{link.relation}</small>{node!.label} →</Button>)}</div></Card></div></div>
}

export function Row({children}:{children:ReactNode}){return <div className="bm-row">{children}</div>}
