import {useEffect,useLayoutEffect,useRef,useId,useState,type ReactNode} from 'react';
import {ArrowUp,FileText,Plus,Search,Square,X,FolderSearch,ChevronDown,Check,Sparkles} from 'lucide-react';
import './prompt.css';
export type PromptAttachment={id:string;name:string;size:number};
export type PromptOption={value:string;description:string};
export function PromptAttachmentChip({file,remove,removeLabel='Remove',locale='en-CA'}:{file:PromptAttachment;remove:()=>void;removeLabel?:string;locale?:string}){return <div className="pc-attachment"><span className="pc-file-icon"><FileText size={19}/></span><div><strong title={file.name}>{file.name}</strong><small>Document · {new Intl.NumberFormat(locale,{maximumFractionDigits:0}).format(file.size/1000)} kB</small></div><button type="button" aria-label={`${removeLabel} ${file.name}`} onClick={remove}><X size={12}/></button></div>}
export function PromptMenu({label,icon,children,disabled=false,open,setOpen}:{label:ReactNode;icon:ReactNode;children:ReactNode;disabled?:boolean;open:boolean;setOpen:(open:boolean)=>void}){const trigger=useRef<HTMLButtonElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const cancel=()=>{if(timer.current)clearTimeout(timer.current)};useEffect(()=>()=>cancel(),[]);return <div className="pc-menu-wrap" onMouseEnter={()=>{cancel();if(!disabled)setOpen(true)}} onMouseLeave={()=>{cancel();timer.current=setTimeout(()=>setOpen(false),160)}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus()}}}><button ref={trigger} type="button" className="pc-mode" aria-expanded={open&&!disabled} disabled={disabled} onClick={()=>setOpen(!open)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);requestAnimationFrame(()=>trigger.current?.parentElement?.querySelector<HTMLInputElement>('input')?.focus())}}}>{icon}{label}<ChevronDown size={11}/></button>{open&&!disabled&&<div className="pc-rich-menu">{children}</div>}</div>}
export function PromptBox({value,onChange,onSubmit,busy=false,onStop,files=[],onFilesChange,mode,modes=[],onModeChange,sources=[],sourceOptions=[],onSourcesChange,label='Your request',placeholder='Ask a question or describe what you need…',caption,labels={}}:{value:string;onChange:(value:string)=>void;onSubmit:()=>void;busy?:boolean;onStop?:()=>void;files?:PromptAttachment[];onFilesChange?:(files:PromptAttachment[])=>void;mode?:string;modes?:PromptOption[];onModeChange?:(mode:string)=>void;sources?:string[];sourceOptions?:PromptOption[];onSourcesChange?:(sources:string[])=>void;label?:string;placeholder?:string;caption?:string;labels?:{attach?:string;send?:string;stop?:string;mode?:string;sources?:string;remove?:string;fileError?:string}}){
 const [menu,setMenu]=useState<string|null>(null);const [error,setError]=useState('');const input=useRef<HTMLInputElement>(null);const textarea=useRef<HTMLTextAreaElement>(null);const id=useId();
 useLayoutEffect(()=>{const el=textarea.current;if(el){el.style.height='auto';el.style.height=Math.min(230,Math.max(87,el.scrollHeight))+'px'}},[value]);
 const submit=()=>{if(value.trim()&&!busy)onSubmit()};const toggle=(name:string)=>(open:boolean)=>setMenu(current=>open?name:current===name?null:current);
 return <div className="pc-demo"><div className={`pc-composer ${busy?'is-running':''}`}><div className="pc-files">{files.map(file=><PromptAttachmentChip key={file.id} file={file} removeLabel={labels.remove} remove={()=>!busy&&onFilesChange?.(files.filter(f=>f.id!==file.id))}/>)}</div><textarea ref={textarea} aria-label={label} placeholder={placeholder} value={value} readOnly={busy} onChange={e=>onChange(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)&&!e.nativeEvent.isComposing){e.preventDefault();submit()}}}/><div className="pc-tools">{onFilesChange&&<><input ref={input} type="file" multiple hidden accept=".pdf,.docx,.txt,.csv,.xlsx" onChange={e=>{const incoming=Array.from(e.target.files??[]);const valid=incoming.filter(f=>f.size<=10_000_000);setError(valid.length<incoming.length?(labels.fileError??'Some files exceed 10 MB. The others were added.'):'');onFilesChange([...files,...valid.map(f=>({id:crypto.randomUUID(),name:f.name,size:f.size}))]);e.target.value=''}}/><span className="pc-attach-trigger"><button type="button" className="pc-plus" aria-label={labels.attach??'Attach files'} onClick={()=>input.current?.click()} disabled={busy}><Plus size={18}/></button><span role="tooltip">{labels.attach??'Attach files'} · 10 MB max.</span></span></>}{mode&&onModeChange&&<PromptMenu open={menu==='mode'} setOpen={toggle('mode')} disabled={busy} icon={<Search size={14}/>} label={mode}><header><strong>{labels.mode??'Work mode'}</strong></header>{modes.map(item=><label className="pc-menu-option" key={item.value}><input type="radio" name={id} checked={mode===item.value} onChange={()=>onModeChange(item.value)}/><span><strong>{item.value}</strong><small>{item.description}</small></span></label>)}</PromptMenu>}{onSourcesChange&&<PromptMenu open={menu==='sources'} setOpen={toggle('sources')} disabled={busy} icon={<FolderSearch size={14}/>} label={<>{labels.sources??'Sources'} <span className="pc-source-count">{sources.length}</span></>}><header><strong>{labels.sources??'Sources'}</strong></header>{sourceOptions.map(item=><label className="pc-menu-option" key={item.value}><input type="checkbox" checked={sources.includes(item.value)} onChange={()=>onSourcesChange(sources.includes(item.value)?sources.filter(s=>s!==item.value):[...sources,item.value])}/><span><strong>{item.value}</strong><small>{item.description}</small></span></label>)}</PromptMenu>}<button type="button" className="pc-send" aria-label={busy?(labels.stop??'Stop'):(labels.send??'Send request')} disabled={busy?!onStop:!value.trim()} onClick={()=>{if(busy)onStop?.();else submit()}}>{busy?<Square size={13}/>:<ArrowUp size={17}/>}</button></div></div><div className="pc-caption"><span>{caption}</span><span>{sources.join(' · ')}</span></div>{error&&<p className="pc-error" role="alert">{error}</p>}</div>
}
export function PromptActionTiles({items,selected,onSelect,disabled=false}:{items:{id:string;title:string;description:string;icon?:ReactNode}[];selected?:string;onSelect:(id:string)=>void;disabled?:boolean}){return <div className="pc-actions">{items.map(item=><button key={item.id} disabled={disabled} aria-pressed={selected===item.id} onClick={()=>onSelect(item.id)}><span className="pc-action-icon">{item.icon??<Sparkles size={18}/>}</span><span className="pc-action-selected" aria-hidden="true"><Check size={12}/></span><strong>{item.title}</strong><span>{item.description}</span></button>)}</div>}

export function PromptPanel({title,description,children}:{title?:string;description?:string;children:ReactNode}){return <div className="pc-demo pc-panel">{title&&<div className="pc-intro"><Sparkles size={20}/><h3>{title}</h3>{description&&<p>{description}</p>}</div>}{children}</div>}
