import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { MotionConfig } from 'motion/react';
import { Check, Copy, Plus } from 'lucide-react';
import { Button, Card, CardHeader, Field, AppSelect, DatePicker, DataTable, DataRow, StatusBadge, MetricCard, EmptyState, AnimatedReveal, ActionFeedback } from 'bm-component-workshop';
import 'bm-component-workshop/style.css';
import './showcase.css';

const rows=[{name:'Atelier Nord',owner:'Alice Martin',amount:480000,status:'review' as const},{name:'Maison Astrée',owner:'Paul Laurent',amount:1250000,status:'progress' as const},{name:'Studio Rivage',owner:'Emma Dubois',amount:320000,status:'success' as const}];
const euro=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0});
function Showcase(){
 const[brand,setBrand]=useState('BM'),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[date,setDate]=useState('2026-09-30'),[open,setOpen]=useState(false),[copied,setCopied]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const root=document.documentElement;const custom=brand==='Client';for(const[key,value]of Object.entries({'--bm-action':custom?'#315e52':'#292a2d','--bm-action-hover':custom?'#417565':'#3a3b3f','--bm-accent':custom?'#337b69':'#287bea','--bm-accent-ink':custom?'#315e52':'#1f71b5','--bm-accent-soft':custom?'#eaf4ef':'#e7f3ff'}))root.style.setProperty(key,value)},[brand]);
 const filtered=rows.filter(row=>row.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(status==='all'||row.status===status));
 return <div className="bm-ui ds-page"><header className="ds-page-header"><div><small>BIBLIOTHÈQUE / THÈME CLAIR</small><h1>Un socle, plusieurs produits.</h1><p>Les mêmes composants, assemblés sans les styles ni les données internes de l’atelier.</p></div><div className="bm-stack"><a href="./dossier-demo.html">Essayer le parcours dossier ↗</a><a href="./index.html">Retour à l’atelier ↗</a></div></header><Card><CardHeader title="Identité du produit" description="La personnalisation modifie les variables communes, y compris les menus ouverts hors de la page."/><div className="bm-row"><AppSelect aria-label="Identité visuelle" value={brand} onValueChange={setBrand}><option value="BM">BM Automation</option><option value="Client">Exemple client · vert</option></AppSelect><Button variant="primary" onClick={()=>setOpen(!open)}><Plus size={14}/>Préparer un dossier</Button><Button disabled>Indisponible</Button><StatusBadge status="success" label="Thème clair"/></div></Card>
 <div className="ds-metrics"><MetricCard label="Dossiers" value={rows.length} detail="Trois étapes représentées"/><MetricCard label="Montant total" value={euro.format(rows.reduce((sum,row)=>sum+row.amount,0))} detail="Données fictives"/><MetricCard label="Prochaine échéance" value={date?new Date(date+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'}):'À définir'} detail="Définie dans le formulaire"/></div>
 <Card><CardHeader title="Dossiers clients" description="Recherche, filtre, tri et déplacement des colonnes." action={<Button small onClick={()=>{setQuery('');setStatus('all')}}>Réinitialiser</Button>}/><div className="ds-filters"><Field label="Rechercher" placeholder="Nom de société" value={query} onChange={e=>setQuery(e.target.value)}/><div className="bm-field"><span>Étape</span><AppSelect aria-label="Filtrer par étape" value={status} onValueChange={setStatus}><option value="all">Toutes les étapes</option><option value="review">En revue</option><option value="progress">En cours</option><option value="success">Terminé</option></AppSelect></div></div>{filtered.length?<div className="bm-table-frame"><DataTable><thead><DataRow><th>Société</th><th>Responsable</th><th className="numeric">Montant</th><th>Étape</th></DataRow></thead><tbody>{filtered.map(row=><DataRow key={row.name}><td>{row.name}</td><td>{row.owner}</td><td className="numeric" data-sort-value={row.amount}>{euro.format(row.amount)}</td><td data-sort-value={row.status}><StatusBadge status={row.status}/></td></DataRow>)}</tbody></DataTable></div>:<EmptyState title="Aucun dossier" description="Essayez un autre nom ou une autre étape." action={<Button onClick={()=>{setQuery('');setStatus('all')}}>Effacer les filtres</Button>}/>}</Card>
 <Card><CardHeader title="Préparer le prochain échange" description="Champs, validation, calendrier et retour d’action partagent les mêmes fondations."/><div className="ds-filters"><Field label="Objet" defaultValue="Point de suivi" required hint="Visible dans le dossier client."/><div className="bm-field"><span>Échéance</span><DatePicker aria-label="Échéance" value={date} onValueChange={setDate}/></div></div><Button aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Masquer les détails':'Afficher les détails'}</Button><AnimatedReveal open={open}><div className="ds-details"><StatusBadge status="pending"/><p>Confirmer les pièces attendues et préparer la synthèse avant le prochain échange.</p></div></AnimatedReveal><div className="bm-row ds-actions"><Button variant="primary" onClick={async()=>{try{await navigator.clipboard.writeText('Point de suivi — '+date);setCopied(true);setError('')}catch{setError('Copie indisponible.')}}}><ActionFeedback state={copied?'copied':'idle'} icon={copied?<Check size={14}/>:<Copy size={14}/>} text={copied?'Copié':'Copier le résumé'}/></Button>{error&&<span role="alert">{error}</span>}</div></Card>
 <footer>Composition de contrôle · aucune connexion externe · préférences de mouvement respectées</footer></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><MotionConfig reducedMotion="user"><Showcase/></MotionConfig></React.StrictMode>);
