import {useId,useState,useRef,useEffect,type ReactNode} from 'react';
import {ChartNoAxesCombined} from 'lucide-react';
import {ChartTooltipArea} from '../components/chart-tooltip';
import './charts.css';
import './workshop-charts.css';
function usePlotWidth(){const ref=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(600);const [height,setHeight]=useState(210);useEffect(()=>{const el=ref.current;if(!el)return;const observer=new ResizeObserver(([entry])=>{setWidth(Math.max(280,entry.contentRect.width));setHeight(Math.max(210,entry.contentRect.height))});observer.observe(el);return()=>observer.disconnect()},[]);return {ref,width,height}}
export function ChartFrame({title,meta,value,caption,children,legend}:{title:string;meta?:string;value?:ReactNode;caption?:string;children:ReactNode;legend?:ReactNode}){return <section className="bm-chart-shell bm-shared-chart"><header className="bm-chart-heading"><span><ChartNoAxesCombined size={17}/>{title}</span>{meta&&<span className="bm-chart-date">{meta}</span>}</header><div className="bm-chart-body">{value!=null&&<div className="bm-chart-summary"><div><strong>{value}</strong><span>{caption}</span></div></div>}{children}{legend&&<footer className="bm-chart-legend">{legend}</footer>}</div></section>}
export function ComparisonChart({title,rows,series,unit='',summary,caption,selected,onSelect,compact=false,depth=false}:{depth?:boolean;compact?:boolean;title:string;rows:{id:string;label:string;values:number[]}[];series:string[];unit?:string;summary?:string;caption?:string;selected?:string;onSelect?:(id:string)=>void}){
 const plot=usePlotWidth();const [active,setActive]=useState<string|null>(null);const uid=useId().replace(/:/g,'');const raw=Math.max(1,...rows.flatMap(r=>r.values));const scale=10**Math.floor(Math.log10(raw));const max=Math.ceil(raw/scale)*scale;const top=20,bottom=180,left=36,width=plot.width-48;const slot=width/Math.max(1,rows.length);const bar=Math.max(4,Math.min(30,(slot-16)/series.length));const y=(v:number)=>bottom-v/max*(bottom-top);
 return <ChartFrame title={title} meta={unit} value={summary} caption={caption} legend={series.map((s,i)=><span key={s}><i style={{background:i===0?'var(--bm-action)':'var(--bm-accent)'}}/>{s}</span>)}><div ref={plot.ref} className="bm-chart-plot" data-compact={compact}><ChartTooltipArea><svg viewBox={`0 0 ${plot.width} 220`} role="group" aria-label={title}><defs><pattern id={uid} width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="7" height="7" fill="var(--bm-accent-soft)"/><rect width="3" height="7" fill="var(--bm-accent)" opacity=".6"/></pattern></defs>{[...new Set([0,1,2,3,4].map(i=>max<=4&&rows.every(r=>r.values.every(Number.isInteger))?Math.round(max*i/4):max*i/4))].map(n=>{return <g key={n}><line x1={left} x2={left+width} y1={y(n)} y2={y(n)} stroke="var(--bm-border)" strokeDasharray="3 6"/><text x={left-12} y={y(n)+4} textAnchor="end">{n.toLocaleString('en',{maximumFractionDigits:1})}</text></g>})}{rows.map((r,i)=>{const x=left+slot*(i+.5);return <g key={r.id} className="bm-chart-point" role={onSelect?'button':'img'} tabIndex={0} aria-pressed={onSelect?selected===r.id:undefined} aria-label={`${r.label}: ${r.values.map((v,j)=>`${series[j]} ${v} ${unit}`).join(', ')}`} data-chart-color="var(--bm-accent)" data-chart-title={r.label} data-chart-value={r.values.map((v,j)=>`${series[j]} ${v.toFixed(1)}`).join(' · ')} data-chart-detail={unit} onClick={()=>onSelect?.(r.id)} onKeyDown={e=>{if(onSelect&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onSelect(r.id)}}} onMouseEnter={()=>setActive(r.id)} onMouseLeave={()=>setActive(null)} onFocus={()=>setActive(r.id)} onBlur={()=>setActive(null)}>{r.values.map((v,j)=>{const bx=x-series.length*bar/2+j*bar+2,bw=Math.max(2,bar-4),by=y(v),fill=j===0?'var(--bm-action)':selected===r.id?`url(#${uid})`:'var(--bm-accent)',d=Math.min(8,bw*.47);return <g key={j} opacity={active&&active!==r.id?.4:1}>{depth&&v>0?<><path d={`M${bx} ${by-d} L${bx+bw/2} ${by} V${bottom} L${bx} ${bottom-d}Z`} fill={fill}/><path d={`M${bx+bw/2} ${by} L${bx+bw} ${by-d} V${bottom-d} L${bx+bw/2} ${bottom}Z`} fill={fill}/><path d={`M${bx+bw/2} ${by} L${bx+bw} ${by-d} V${bottom-d} L${bx+bw/2} ${bottom}Z`} fill="black" opacity=".18"/><path d={`M${bx} ${by-d} L${bx+bw/2} ${by-2*d} L${bx+bw} ${by-d} L${bx+bw/2} ${by}Z`} fill={fill}/><path d={`M${bx} ${by-d} L${bx+bw/2} ${by-2*d} L${bx+bw} ${by-d} L${bx+bw/2} ${by}Z`} fill="white" opacity=".3"/><path d={`M${bx+bw/2} ${by} V${bottom}`} stroke="white" strokeOpacity=".35" strokeWidth=".7"/></>:<rect x={bx} y={by} width={bw} height={Math.max(0,bottom-by)} rx={5} fill={fill}/>}</g>})}<text x={x} y={bottom+24} textAnchor="middle" style={{fontWeight:selected===r.id?600:400,fill:selected===r.id?'var(--bm-accent-ink)':undefined}}>{compact&&slot<100&&r.label.includes(" ")?<><tspan x={x}>{r.label.split(" ")[0]}</tspan><tspan x={x} dy="12">{r.label.split(" ").slice(1).join(" ")}</tspan></>:r.label}</text></g>})}</svg></ChartTooltipArea></div></ChartFrame>
}
export function DistributionChart({title,rows,unit='%',caption='Total',compact=false}:{compact?:boolean;title:string;rows:{label:string;value:number}[];unit?:string;caption?:string}){const [active,setActive]=useState<number|null>(null);const total=rows.reduce((s,r)=>s+r.value,0);const colors=['var(--bm-action)','var(--bm-accent)','var(--bm-chart-third,#6a9ca7)','var(--bm-chart-fourth,#a7c4cc)','var(--bm-chart-fifth,#d1e1e5)'];let sum=0;const ends=rows.map(r=>(sum+=r.value));return <ChartFrame title={title} legend={<span>{caption} · {total}{unit==='%'?unit:` ${unit}`}</span>}><div className="bm-donut-layout" data-compact={compact}><svg viewBox="20 20 200 200" role="img" aria-label={rows.map(r=>`${r.label}: ${r.value}${unit}`).join(', ')}>{Array.from({length:100},(_,i)=>{const angle=(i*3.6-90)*Math.PI/180;const index=ends.findIndex(v=>(i+.5)*total/100<v);return <line key={i} x1={120+72*Math.cos(angle)} y1={120+72*Math.sin(angle)} x2={120+93*Math.cos(angle)} y2={120+93*Math.sin(angle)} stroke={total?colors[Math.max(0,index)%colors.length]:'var(--bm-border)'} strokeWidth="3" strokeLinecap="round" opacity={active===null||active===index?1:.15}/>})}<text x="120" y="120" textAnchor="middle" className="bm-donut-total">{active===null?total:rows[active]?.value}{unit==='%'?unit:''}</text><text x="120" y="143" textAnchor="middle">{active===null?caption:rows[active].label}</text></svg><div className="bm-donut-legend">{rows.map((r,i)=><button key={r.label} type="button" aria-pressed={active===i} onMouseEnter={()=>setActive(i)} onMouseLeave={()=>setActive(null)} onFocus={()=>setActive(i)} onBlur={()=>setActive(null)} onClick={()=>setActive(active===i?null:i)}><i style={{background:colors[i%colors.length]}}/><span>{r.label}</span><strong>{r.value}{unit==='%'?unit:''}</strong></button>)}</div></div></ChartFrame>}

export function TrendChart({title,rows,unit='%',caption}:{title:string;rows:{label:string;value:number;detail?:string}[];unit?:string;caption?:string}){
 const plot=usePlotWidth();const id=useId().replace(/:/g,'');const min=Math.min(0,...rows.map(r=>r.value));const max=Math.max(1,...rows.map(r=>r.value))*1.15;const left=36,right=plot.width-20,top=16,bottom=plot.height-40;
 const x=(i:number)=>rows.length===1?(left+right)/2:left+i*(right-left)/Math.max(1,rows.length-1);const y=(v:number)=>bottom-(v-min)/(max-min)*(bottom-top);const line=rows.map((r,i)=>`${i?'L':'M'}${x(i)},${y(r.value)}`).join(' ');
 return <ChartFrame title={title} meta={unit} legend={caption&&<span>{caption}</span>}><div ref={plot.ref} className="bm-trend-plot"><ChartTooltipArea><svg viewBox={`0 0 ${plot.width} ${plot.height}`} role="group" aria-label={title}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--bm-accent)" stopOpacity=".2"/><stop offset="1" stopColor="var(--bm-accent)" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=>{const v=min+(max-min)*i/3;return <g key={i}><line x1={left} x2={right} y1={y(v)} y2={y(v)} stroke="var(--bm-border)" strokeDasharray="3 6"/><text x={left-8} y={y(v)+3} textAnchor="end">{v.toFixed(0)}</text></g>})}{rows.length>0&&<><path d={`${line} L${x(rows.length-1)},${bottom} L${x(0)},${bottom} Z`} fill={`url(#${id})`}/><path d={line} fill="none" stroke="var(--bm-accent)" strokeWidth="2" strokeLinejoin="round"/></>}{rows.map((r,i)=><g key={r.label}><circle cx={x(i)} cy={y(r.value)} r="4" fill="var(--bm-surface)" stroke="var(--bm-accent)" strokeWidth="2" tabIndex={0} role="img" aria-label={`${r.label}: ${r.value}${unit}`} data-chart-title={r.label} data-chart-value={`${r.value.toFixed(1)}${unit}`} data-chart-detail={r.detail} data-chart-color="var(--bm-accent)"/>{(i===0||i===rows.length-1||i%Math.max(1,Math.ceil(rows.length/5))===0)&&<text x={x(i)} y={plot.height-14} textAnchor={i===0?'start':i===rows.length-1?'end':'middle'}>{r.label}</text>}</g>)}</svg></ChartTooltipArea></div></ChartFrame>
}
