import {useState,type ReactNode} from 'react';
import {ChevronDown} from 'lucide-react';
import './workspace.css';

export type WorkspaceNavItem={id:string;label:string;icon?:ReactNode;children?:{id:string;label:string;icon?:ReactNode}[]};

export function WorkspaceShell({brand,items,active,onNavigate,toolbar,footer,children,density='comfortable'}:{brand:ReactNode;items:WorkspaceNavItem[];active:string;onNavigate:(id:string)=>void;toolbar?:ReactNode;footer?:ReactNode;children:ReactNode;density?:'comfortable'|'compact'}){
 const [expanded,setExpanded]=useState<string|null>(null);
 return <div className="bm-ui bm-workspace" data-density={density}><aside className="bm-workspace-nav"><div className="bm-workspace-brand">{brand}</div><nav aria-label="Primary navigation">{items.map(item=>{const childActive=item.children?.some(child=>child.id===active)??false;const open=childActive||expanded===item.id;return <div key={item.id} className="bm-workspace-nav-group" data-open={open} data-active={childActive||active===item.id} onMouseEnter={()=>item.children&&setExpanded(item.id)} onMouseLeave={()=>setExpanded(current=>current===item.id?null:current)} onFocus={()=>item.children&&setExpanded(item.id)} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))setExpanded(current=>current===item.id?null:current)}}><button aria-current={active===item.id?'page':undefined} aria-expanded={item.children?open:undefined} onClick={()=>onNavigate(item.id)} onKeyDown={event=>{if(event.key==='Escape'){setExpanded(null);event.currentTarget.focus()}}}>{item.icon}<span>{item.label}</span>{item.children&&<ChevronDown className="bm-workspace-nav-chevron" aria-hidden="true"/>}</button>{item.children&&<div className="bm-workspace-subnav" aria-hidden={!open}><div>{item.children.map(child=><button key={child.id} tabIndex={open?0:-1} aria-current={active===child.id?'page':undefined} onClick={()=>onNavigate(child.id)}>{child.icon}<span>{child.label}</span></button>)}</div></div>}</div>})}</nav></aside><div className="bm-workspace-main"><header className="bm-workspace-toolbar">{toolbar}</header><main id="mainContent">{children}</main><footer className="bm-workspace-footer">{footer}</footer></div></div>;
}
