import { AnimatedReveal } from "./ui/animated-reveal";
import { useId, useState } from "react";
import { Bot, Check, ChevronDown, ChevronRight, FileText, LoaderCircle, Pencil, RotateCcw, Search, X } from "lucide-react";
import "./agent-supervision.css";
type Agent={id:string;name:string;status:"running"|"done"|"failed";summary:string;file:string;actions:number;description:string};
const initial:Agent[]=[
{id:"synthese",name:"Synthèse",status:"done",summary:"Synthèse du dossier préparée.",file:"atlas/synthese.md",actions:3,description:"Les trois points de décision sont regroupés. Les montants sont conservés avec leurs unités."},
{id:"finance",name:"Finance",status:"running",summary:"Lecture des données financières",file:"atlas/finances.csv",actions:3,description:"Vérification de la cohérence des montants et des périodes avant préparation du récapitulatif financier."},
{id:"documents",name:"Documents",status:"running",summary:"Classement des pièces reçues",file:"atlas/documents.json",actions:3,description:"Classement des pièces de démonstration par type, avec conservation du nom d’origine et de la provenance."},
{id:"controle",name:"Contrôle",status:"failed",summary:"Interrompu : deux références identiques.",file:"atlas/controle.md",actions:2,description:"Deux pièces portent la même référence. La simulation est arrêtée pour conserver les documents et permettre une nouvelle tentative."},
{id:"recherche",name:"Recherche",status:"running",summary:"Recoupement des informations",file:"atlas/sources.md",actions:3,description:"Comparaison des informations internes de démonstration. Aucune recherche externe n’est effectuée."}];
const statusName={running:"En cours",done:"Terminé",failed:"Interrompu"};
function StateIcon({status}:{status:Agent["status"]}){return status==="done"?<Check size={13}/>:status==="failed"?<X size={13}/>:<LoaderCircle size={13}/>}
export function AgentSupervisionDemo(){
 const [agents,setAgents]=useState(initial),[selected,setSelected]=useState<string|null>("documents"),[expanded,setExpanded]=useState(true);
 const uid=useId(),current=agents.find(a=>a.id===selected),running=agents.filter(a=>a.status==="running").length,done=agents.filter(a=>a.status==="done").length,failed=agents.filter(a=>a.status==="failed").length;
 const update=(id:string,status:Agent["status"])=>setAgents(items=>items.map(a=>a.id===id?{...a,status,actions:a.actions+1,summary:status==="done"?"Traitement de démonstration terminé.":"Nouvelle tentative de démonstration."}:a));
 return <section className="bm-supervision"><header><button type="button" aria-expanded={expanded} aria-controls={uid+"-body"} onClick={()=>setExpanded(!expanded)}><Bot size={16}/><strong>Agents</strong><span>{running} en cours · {done} terminé{done>1?"s":""} · {failed} interrompu{failed>1?"s":""}</span><small>{agents.reduce((sum,a)=>sum+a.actions,0)} actions</small><ChevronDown size={15}/></button></header><div className="bm-supervision-progress" role="progressbar" aria-label="Agents terminés" aria-valuemin={0} aria-valuemax={agents.length} aria-valuenow={done}><i style={{width:done/agents.length*100+"%"}}/></div>
 <AnimatedReveal open={expanded}><div id={uid+"-body"}><div className="bm-supervision-scroll"><div className="bm-supervision-fan"><svg viewBox="0 0 146 232" aria-hidden="true">{agents.map((a,i)=><g key={a.id}><path d={"M104 116 C126 116,119 "+(24+i*46)+",141 "+(24+i*46)} className={a.status}/><circle cx="141" cy={24+i*46} r="2.4" className={a.status}/></g>)}</svg><div className="bm-supervision-origin"><Bot size={14}/><strong>Agent</strong><i/></div><div className="bm-supervision-rows">{agents.map(a=><button type="button" key={a.id} className={a.status+" "+(selected===a.id?"selected":"")} aria-expanded={selected===a.id} aria-controls={uid+"-detail"} onClick={()=>setSelected(selected===a.id?null:a.id)}><span className={"bm-agent-status "+a.status} aria-label={statusName[a.status]}><StateIcon status={a.status}/></span><strong>{a.name}</strong><span>{a.summary}</span>{selected===a.id?<ChevronDown size={13}/>:<ChevronRight size={13}/>}</button>)}</div></div></div>{current&&<div id={uid+"-detail"} className="bm-supervision-detail" role="region" aria-label={"Détail de l’agent "+current.name}><div className="bm-supervision-detail-heading"><strong>{current.name} <span>{statusName[current.status]}</span></strong><span>{current.actions} actions</span></div><p>{current.description}</p><dl><div><dt><Search size={12}/>Rechercher</dt><dd>Dossier Atlas · informations internes</dd></div><div><dt><FileText size={12}/>Lire</dt><dd>{current.file}</dd></div><div><dt><Pencil size={12}/>{current.status==="done"?"Résultat":"Préparer"}</dt><dd>{current.status==="done"?"Version de démonstration prête":"Brouillon de travail local"}</dd></div></dl><div className="bm-supervision-detail-actions">{current.status==="failed"?<button type="button" onClick={()=>update(current.id,"running")}><RotateCcw size={12}/>Simuler une nouvelle tentative</button>:current.status==="running"?<button type="button" onClick={()=>update(current.id,"done")}><Check size={12}/>Simuler la fin du traitement</button>:<button type="button" aria-disabled="true"><Check size={12}/>Traitement terminé</button>}</div></div>}</div></AnimatedReveal>
 <footer><span role="status">Supervision simulée · aucun agent externe lancé</span><button type="button" onClick={()=>{setAgents(initial);setSelected("documents");setExpanded(true)}}>Réinitialiser</button></footer></section>;
}
