import { AnimatedReveal } from "./ui/animated-reveal";
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, CheckCheck, ChevronDown, Clock3, FileText, ReceiptText, X } from 'lucide-react';
import { Button } from './ui/button';
import { Overlay } from './panels-demo';
import './approval-demo.css';
export function ApprovalDemo(){
 const [decision,setDecision]=useState<'pending'|'approved'|'rejected'>('pending');
 const [rejecting,setRejecting]=useState(false),[reason,setReason]=useState(''),[document,setDocument]=useState(false),[history,setHistory]=useState(false);
 const result=useRef<HTMLDivElement>(null),rejectButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(decision!=='pending')result.current?.focus()},[decision]);
 function reset(){setDecision('pending');setRejecting(false);setReason('');setHistory(false)}
 return <section className="approval-v2" aria-label="Validation de la facture Lumen Conseil">
  <header className="ap-heading"><span className="ap-document-icon"><ReceiptText size={20}/></span><div><span className="ap-eyebrow">FACTURE FOURNISSEUR · DOSSIER ATLAS</span><h3>Honoraires de conseil</h3></div><span className={`ap-status ${decision}`}>{decision==='pending'?<Clock3 size={12}/>:decision==='approved'?<Check size={12}/>:<X size={12}/>} {decision==='pending'?'À votre tour':decision==='approved'?'Approuvée':'Refusée'}</span></header>
  <div className="ap-amount"><strong>48 000 <span>€</span></strong><span>TTC<small>40 000 € HT + 8 000 € de TVA</small></span></div>
  <div className="ap-parties"><div><span className="ap-monogram buyer">AN</span><span><small>Société facturée</small><strong>Atelier Nord</strong></span></div><ArrowRight size={18} aria-label="doit régler"/><div><span className="ap-monogram supplier">LC</span><span><small>Fournisseur à régler</small><strong>Lumen Conseil</strong></span></div></div>
  <p className="ap-purpose">Mission de conseil — préparation du dossier de cession Atlas.</p>
  <button className="ap-file" onClick={()=>setDocument(true)}><span className="ap-pdf"><FileText size={17}/><small>PDF</small></span><span><strong>Facture LC-2026-014</strong><small>Émise le 14 sept. · Échéance le 30 sept. 2026</small></span><span className="ap-file-action">Consulter <ArrowRight size={13}/></span></button>
  <div className="ap-section-title"><h4>Circuit de validation</h4><span>{decision==='approved'?'2 validations sur 2':decision==='rejected'?'Circuit interrompu':'1 validation sur 2'}</span></div>
  <ol className="ap-steps"><li className="complete"><span className="ap-step-mark"><Check size={13}/></span><img src="avatars/alice.svg" alt=""/><div><strong>Service réalisé</strong><small>Alice Martin · Responsable du dossier</small></div><span className="ap-step-note">Validé<small>15 sept. · 09:42</small></span></li><li className={decision==='pending'?'current':decision==='approved'?'complete':'rejected'}><span className="ap-step-mark">{decision==='approved'?<Check size={13}/>:decision==='rejected'?<X size={13}/>:2}</span><span className="ap-you">VO</span><div><strong>Validation financière</strong><small>Vous · Responsable financier</small></div><span className="ap-step-note">{decision==='pending'?'À faire':decision==='approved'?'Validé':'Refusé'}</span></li></ol>
  <div className={`ap-decision ${decision}`} ref={result} tabIndex={-1} role="status"><span className="ap-decision-icon">{decision==='pending'?<ReceiptText size={17}/>:decision==='approved'?<CheckCheck size={18}/>:<X size={18}/>}</span><div><strong>{decision==='pending'?'Votre validation est la dernière étape':decision==='approved'?'Facture approuvée pour comptabilisation':'Facture renvoyée pour correction'}</strong><p>{decision==='pending'?'Approuver autorise sa transmission à la comptabilité. Le règlement reste une étape distincte.':decision==='approved'?'Les deux validations sont obtenues. Aucun paiement n’a été effectué.':reason}</p></div></div>
  {decision==='pending'&&(!rejecting?<div className="ap-actions"><Button ref={rejectButton} onClick={()=>setRejecting(true)}>Refuser</Button><Button variant="primary" onClick={()=>setDecision('approved')}><Check size={14}/>Approuver la facture</Button></div>:<form className="ap-reject" onSubmit={e=>{e.preventDefault();if(reason.trim()){setDecision('rejected');setRejecting(false)}}}><label htmlFor="ap-reason">Que faut-il corriger ?</label><textarea id="ap-reason" autoFocus maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex. Le montant ne correspond pas au devis signé." required/><div><Button type="button" onClick={()=>{setRejecting(false);requestAnimationFrame(()=>rejectButton.current?.focus())}}>Annuler</Button><Button type="submit" disabled={!reason.trim()}>Confirmer le refus</Button></div></form>)}
  <div className="ap-history"><button aria-expanded={history} onClick={()=>setHistory(!history)}><Clock3 size={13}/><strong>Historique</strong><span>{decision==='pending'?2:3} événements</span><ChevronDown size={14} className={history?'open':''}/></button><AnimatedReveal open={history}><ol>{decision!=='pending'&&<li><span className={`ap-event ${decision}`}>{decision==='approved'?<Check size={12}/>:<X size={12}/>}</span><div><strong>{decision==='approved'?'Vous avez approuvé la facture':'Vous avez refusé la facture'}</strong><p>{decision==='rejected'?reason:'Validation financière terminée.'}</p></div><time>À l’instant</time></li>}<li><span className="ap-event approved"><Check size={12}/></span><div><strong>Alice a confirmé le service réalisé</strong><p>Validation opérationnelle</p></div><time>15 sept. · 09:42</time></li><li><span className="ap-event"><FileText size={12}/></span><div><strong>Alice a soumis la facture</strong><p>LC-2026-014 · 48 000 € TTC</p></div><time>15 sept. · 09:30</time></li></ol></AnimatedReveal></div>
  <footer className="ap-demo-footer"><span>Données fictives · décision simulée</span><button onClick={reset}>Réinitialiser</button></footer>
  {document&&<Overlay title="Facture LC-2026-014" onClose={()=>setDocument(false)}><div className="ap-invoice"><span className="ap-eyebrow">DOCUMENT DE DÉMONSTRATION</span><h3>Lumen Conseil</h3><p>Facturé à <strong>Atelier Nord</strong></p><dl><div><dt>Émission</dt><dd>14 septembre 2026</dd></div><div><dt>Échéance</dt><dd>30 septembre 2026</dd></div></dl><hr/><p>Mission de conseil — préparation du dossier de cession Atlas.</p><dl><div><dt>Honoraires HT</dt><dd>40 000 €</dd></div><div><dt>TVA · 20 %</dt><dd>8 000 €</dd></div><div className="total"><dt>Total TTC</dt><dd>48 000 €</dd></div></dl><p className="ap-invoice-note">Aperçu fictif pour évaluer le composant.</p></div><footer><Button onClick={()=>setDocument(false)}>Fermer l’aperçu</Button></footer></Overlay>}
 </section>
}
