import { AnimatedReveal } from "./ui/animated-reveal";
import { DataTable, DataRow } from "./ui/data-table";
import { AppSelect } from "./ui/app-select";
import { useEffect, useId, useState } from 'react';
import { Check, ChevronDown, FileText, Hash, RotateCcw, TriangleAlert, WandSparkles } from 'lucide-react';
import { Button } from './ui/button';
import { StatusBadge } from './status-badge';
import './business-details.css';
const euro=(v:number)=>v.toLocaleString('fr-FR',{style:'currency',currency:'EUR'});
export function InvoiceDemo(){const[qty,setQty]=useState(2),[rate,setRate]=useState(20),[paid,setPaid]=useState(false);const subtotal=qty*1250,tax=Math.round(subtotal*rate)/100;return <div className="invoice-demo"><header><div><h3>FACT-2026-014 <StatusBadge status={paid?'success':'pending'} label={paid?'Réglée · démo':'En attente'}/></h3><p>Émise le 15 septembre 2026</p></div></header><div className="invoice-meta"><div><small>Période</small><strong>Septembre 2026</strong><span>Du 1 au 30 septembre</span></div><div><small>Facturé à</small><strong>Atelier Nord</strong><span>contact@example.com</span></div><div><small>Mode de règlement</small><strong>Virement</strong><span>Échéance à 30 jours</span></div></div><div className="invoice-scroll"><DataTable><thead><DataRow><th>Prestation</th><th>Quantité</th><th>Prix unitaire</th><th>Montant HT</th></DataRow></thead><tbody><DataRow><td><strong>Journée de conseil</strong><small>Préparation du dossier</small></td><td><input type="number" aria-label="Nombre de journées" value={qty} min="1" max="30" onChange={e=>{setQty(Math.min(30,Math.max(1,Math.round(Number(e.target.value)||1))));setPaid(false)}}/></td><td>{euro(1250)}</td><td>{euro(subtotal)}</td></DataRow></tbody></DataTable></div><dl className="invoice-totals"><div><dt>Sous-total HT</dt><dd>{euro(subtotal)}</dd></div><div><dt>TVA <AppSelect aria-label="Taux de TVA de démonstration" value={rate} onValueChange={e=>{setRate(Number(e));setPaid(false)}}><option value="0">0 %</option><option value="10">10 %</option><option value="20">20 %</option></AppSelect></dt><dd>{euro(tax)}</dd></div><div><dt>Total TTC</dt><dd>{euro(subtotal+tax)}</dd></div></dl><footer><small>Exemple fictif · aucun paiement</small><Button small onClick={()=>setPaid(!paid)}>{paid?'Réinitialiser':'Simuler le règlement'}</Button></footer></div>}
export function ChoiceCardsDemo(){const[type,setType]=useState('Texte'),[name,setName]=useState(''),[value,setValue]=useState(''),[saved,setSaved]=useState(false);const valid=/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)&& (type==='Texte'||value===''||Number.isFinite(Number(value)));return <form className="choice-demo" onSubmit={e=>{e.preventDefault();if(valid)setSaved(true)}}><h3>Créer un champ</h3><label>Nom du champ <input required value={name} onChange={e=>{setName(e.target.value.replaceAll(' ','_'));setSaved(false)}} placeholder="ex. montant_mission" pattern="[a-zA-Z_][a-zA-Z0-9_]*"/></label><p>Lettres, chiffres et tirets bas. Les espaces sont convertis.</p><fieldset><legend>Type de valeur</legend><div className="choice-grid">{[{name:'Texte',icon:FileText,desc:'Noms, descriptions et messages.'},{name:'Nombre',icon:Hash,desc:'Montants, quantités et scores.'}].map(c=><label className={type===c.name?'active':''} key={c.name}><input type="radio" name="field-type" checked={type===c.name} onChange={()=>{setType(c.name);setValue('');setSaved(false)}}/><c.icon size={18}/><strong>{c.name}</strong><span>{c.desc}</span></label>)}</div></fieldset><label>Valeur par défaut <input type={type==='Nombre'?'number':'text'} step="any" value={value} onChange={e=>{setValue(e.target.value);setSaved(false)}} placeholder={type==='Texte'?'Valeur utilisée si le champ est vide':'0'}/></label><footer><span role="status">{saved?`Champ ${name} créé dans la démo.`:''}</span><Button type="submit" variant="primary" disabled={!valid||saved}>{saved?<Check size={14}/>:<Hash size={14}/>}{saved?'Champ créé':'Créer le champ'}</Button></footer></form>}
export function RecoveryDemo(){const detailId=useId();const[state,setState]=useState<'failed'|'loading'|'success'>('failed'),[detail,setDetail]=useState(false);useEffect(()=>{if(state!=='loading')return;const t=setTimeout(()=>setState('success'),1300);return()=>clearTimeout(t)},[state]);return <div className={`recovery-demo ${state}`}><header>{state==='success'?<Check size={16}/>:<TriangleAlert size={16}/>}<strong>{state==='success'?'Import vérifié':state==='loading'?'Vérification en cours…':'Import interrompu'}</strong><span>{state==='success'?'Vérifié':'Format'}</span></header><p>{state==='success'?'Les 3 lignes de démonstration sont prêtes à être importées.':'Deux colonnes portent le même nom. Renommez la seconde colonne « Montant » pour poursuivre.'}</p><div className="recovery-actions"><Button small disabled={state==='loading'} onClick={()=>setState(state==='success'?'failed':'loading')}>{state==='success'?<RotateCcw size={12}/>:<WandSparkles size={12}/>} {state==='success'?'Recommencer':'Simuler la correction'}</Button><Button small aria-expanded={detail} aria-controls={detailId} onClick={()=>setDetail(!detail)}>Détails <ChevronDown size={12}/></Button></div><AnimatedReveal open={detail}><pre id={detailId}>Fichier : societes-exemple.csv{'\n'}Colonne 2 : Montant{'\n'}Colonne 4 : {state==='success'?'Montant complémentaire':'Montant'}{'\n'}Code : {state==='success'?'VALIDATED':'DUPLICATE_COLUMN'}{'\n'}Les données du fichier sont conservées.</pre></AnimatedReveal><span role="status" className="recovery-status">{state==='loading'?'Simulation en cours.':state==='success'?'Correction simulée terminée.':'Simulation locale · erreur récupérable.'}</span></div>}
