import { useId, useState } from "react";
import { Bot, Brain, Cpu, Globe, Search, Truck, Zap } from "lucide-react";
import "./charts-variants.css";
export const detailedModes = ["Pixels", "Miroir", "Répartition", "Nuage", "Modèles", "Catégories", "Objectif", "Canaux", "Livraisons"] as const;
export type DetailedChartMode = typeof detailedModes[number];
const months=["Jan","Fév","Mar","Avr","Mai","Juin","Juil","Août","Sep","Oct","Nov","Déc"];
const palette=["#567bf2","#9367d7","#e79746","#4ca99b"];
const groups=[{name:"Production",value:50},{name:"Staging",value:20},{name:"Développement",value:15},{name:"Tests",value:15}];
export function DetailedChartVariants({mode,empty}:{mode:DetailedChartMode;empty:boolean}){
 const [tip,setTip]=useState("");const [selected,setSelected]=useState<number|null>(null);const [percent,setPercent]=useState(false);const uid=useId().replace(/:/g,"");
 const inspect=(label:string)=>({tabIndex:0,onFocus:()=>setTip(label),onBlur:()=>setTip(""),onMouseEnter:()=>setTip(label),onMouseLeave:()=>setTip("")});
 return <section className="bm-chart-shell bm-detailed"><header className="bm-chart-heading">{mode}<span className="bm-chart-date">Données fictives · 2026</span></header><div className="bm-chart-body"><div className="bm-extra-tip" role="status">{tip||"Survolez une valeur ou parcourez avec Tab."}</div>{empty?<div className="bm-chart-empty"><strong>Aucune donnée sur cette période</strong></div>:<>
 {mode==="Pixels"&&<svg viewBox="0 0 600 275" role="group" aria-label="Histogramme en carrés"><text x="35" y="15">Dossiers · 1 carré = 1 dossier</text>{[0,5,10,15,20].map(n=><text key={n} x="25" y={233-n*10.5} textAnchor="end">{n}</text>)}{months.map((m,i)=>{const done=[6,9,8,5,9,11,13,10,12,14,10,15][i],pending=[4,3,5,4,6,5,4,6,4,3,5,4][i];return <g key={m} {...inspect(m+" : "+done+" finalisés, "+pending+" en cours, "+(done+pending)+" reçus")} className="bm-chart-point">{Array.from({length:20},(_,j)=><rect key={j} x={40+i*45} y={225-j*10.5} width="31" height="8" rx="1" fill={j<done?"#303843":j<done+pending?"#a9b2be":"#f0f2f4"}/>)}<text x={55+i*45} y="256" textAnchor="middle">{m}</text><rect className="bm-chart-focus" x={36+i*45} y="23" width="40" height="216" rx="3"/></g>})}</svg>}
 {mode==="Miroir"&&<svg viewBox="0 0 600 290" role="group" aria-label="Trésorerie mensuelle, entrées positives sorties négatives"><text x="42" y="15">k€</text>{[-40,-20,0,20,40].map(n=><g key={n}><line x1="42" x2="575" y1={140-n*2.4} y2={140-n*2.4} stroke={n===0?"#8d9aa9":"#e8edf1"}/><text x="30" y={144-n*2.4} textAnchor="end">{n}</text></g>)}{months.map((m,i)=>{const a=[20,25,23,30,34,28,36,31,39,35,32,40][i],b=[15,19,18,22,26,21,28,24,29,26,25,31][i];return <g key={m} {...inspect(m+" : entrées "+a+" k€, sorties −"+b+" k€, solde +"+(a-b)+" k€")} className="bm-chart-point"><rect x={48+i*44} y={140-a*2.4} width="23" height={a*2.4} rx="3" fill="#4ca9b9"/><rect x={48+i*44} y="140" width="23" height={b*2.4} rx="3" fill="#b7dce3"/><text x={59+i*44} y="270" textAnchor="middle">{m}</text></g>})}</svg>}
 {mode==="Répartition"&&<div><div className="bm-detailed-summary"><strong>100 <small>requêtes</small></strong><button type="button" onClick={()=>setPercent(v=>!v)}>{percent?"Afficher les nombres":"Afficher les pourcentages"}</button></div><div className="bm-detailed-segments" role="img" aria-label="100 requêtes : Production 50, Staging 20, Développement 15, Tests 15">{groups.flatMap((s,i)=>Array.from({length:s.value},(_,j)=><i key={i+"-"+j} style={{background:palette[i],opacity:selected===null||selected===i?1:.16}}/>))}</div><div className="bm-detailed-legend">{groups.map((s,i)=><button type="button" key={s.name} aria-pressed={selected===i} onClick={()=>setSelected(selected===i?null:i)}><i style={{background:palette[i]}}/>{s.name}<strong>{s.value}{percent?" %":""}</strong></button>)}</div><p>Cliquez une légende pour isoler sa contribution.</p></div>}
 {mode==="Nuage"&&<svg viewBox="0 0 600 290" role="group" aria-label="Offres : prix mensuel en euros et capacité dossiers par mois">{[0,50,100,150,200].map(n=><g key={n}><line x1="48" x2="562" y1={240-n} y2={240-n} stroke="#e8edf1" strokeDasharray="3 5"/><text x="35" y={244-n} textAnchor="end">{n}</text></g>)}{[0,100,200,300,400,500].map(n=><text key={n} x={48+n} y="260" textAnchor="middle">{n}</text>)}<text x="48" y="18">Capacité · dossiers / mois</text><text x="550" y="283" textAnchor="end">Prix mensuel · €</text>{[[80,40],[110,65],[180,60],[230,115],[270,80],[290,150],[340,120],[400,165],[450,180],[200,140]].map(([price,capacity],i)=><g key={i} {...inspect((i===9?"Votre offre":"Offre "+(i+1))+" : "+price+" €/mois, capacité "+capacity+" dossiers/mois")} className="bm-chart-point"><circle cx={48+price} cy={240-capacity} r={i===9?8:5} fill={i===9?"#5478e8":i%2?"#e99b53":"#5cae98"} stroke="white" strokeWidth="2"/>{i===9&&<text x={48+price} y={220-capacity} textAnchor="middle">Votre offre</text>}</g>)}</svg>}
 {mode==="Modèles"&&<div className="bm-detailed-models">{[Brain,Bot,Cpu,Zap].map((Icon,i)=><div key={i} className="bm-detailed-model" {...inspect("Modèle "+String.fromCharCode(65+i)+" : score fictif "+[8,6,9,5][i]+" sur 10")}><span><Icon size={18}/><strong>Modèle {String.fromCharCode(65+i)}</strong></span><div className="bm-detailed-rating" role="meter" aria-label={"Score du modèle "+String.fromCharCode(65+i)} aria-valuemin={0} aria-valuemax={10} aria-valuenow={[8,6,9,5][i]}>{Array.from({length:10},(_,n)=><i key={n} style={{background:n<[8,6,9,5][i]?palette[i]:undefined}}/>)}</div><strong>{[8,6,9,5][i]}<small>/10</small></strong></div>)}<p>Jeu de démonstration · aucune mesure de modèles commerciaux.</p></div>}
 {mode==="Catégories"&&<svg viewBox="0 0 600 290" role="group" aria-label="Demandes par outil"><text x="40" y="18">Demandes</text>{[0,25,50,75,100].map(n=><g key={n}><line x1="40" x2="564" y1={240-n*1.8} y2={240-n*1.8} stroke="#e8edf1" strokeDasharray="3 5"/><text x="29" y={244-n*1.8} textAnchor="end">{n}</text></g>)}{[Search,Globe,Bot,Cpu].map((Icon,i)=>{const n=[80,55,95,40][i],x=80+i*130;return <g key={i} {...inspect(["Recherche","Web","Assistant","Calcul"][i]+" : "+n+" demandes")} className="bm-chart-point"><rect x={x} y={240-n*1.8} width="65" height={n*1.8} rx="5" fill="#d4dce6"/><rect x={x+19} y={204-n*1.8} width="28" height="28" rx="8" fill="#303846"/><Icon x={x+25} y={210-n*1.8} width="16" height="16" color="white"/><text x={x+32} y="268" textAnchor="middle">{["Recherche","Web","Assistant","Calcul"][i]}</text></g>})}</svg>}
 {mode==="Objectif"&&<><svg viewBox="0 0 600 265" role="group" aria-label="Objectif hebdomadaire 80 dossiers">{[0,20,40,60,80,100].map(n=><g key={n}><line x1="45" x2="558" y1={220-n*1.8} y2={220-n*1.8} stroke="#e8edf1"/><text x="32" y={224-n*1.8} textAnchor="end">{n}</text></g>)}<line x1="45" x2="558" y1="76" y2="76" stroke="#c77872" strokeDasharray="5 5"/><text x="551" y="67" textAnchor="end">Objectif · 80 dossiers</text><polyline points={[30,45,40,63,58,77,92].map((n,i)=>(48+i*84)+","+(220-n*1.8)).join(" ")} fill="none" stroke="#687ea7" strokeWidth="2.5"/>{[30,45,40,63,58,77,92].map((n,i)=><g key={i} {...inspect("Semaine "+(i+1)+" : "+n+" dossiers, écart "+(n-80)+" à l’objectif de 80")}><circle cx={48+i*84} cy={220-n*1.8} r="5" fill="white" stroke="#687ea7" strokeWidth="2"/><text x={48+i*84} y="247" textAnchor="middle">S{i+1}</text></g>)}</svg><div className="bm-detailed-country"><p>Répartition géographique · autre série, échelle 0–100 dossiers</p>{[["France",92],["Allemagne",61],["Espagne",37]].map(([name,n])=><div key={name} style={{background:"linear-gradient(to right,#edf2fa "+n+"%,transparent "+n+"%)"}}><span>{name}</span><strong>{n} dossiers</strong></div>)}</div></>}
 {mode==="Canaux"&&<div className="bm-detailed-channels">{[["Recherche",26800],["Réseaux",16400],["Partenaires",12200]].map(([label,n],i)=><div key={label} {...inspect(label+" : "+Number(n).toLocaleString("fr-FR")+" € sur une échelle commune de 40 000 €")}><div><span>{label}</span><strong>{Number(n).toLocaleString("fr-FR")} €</strong></div><svg viewBox="0 0 520 30" role="img" aria-label={label+" "+n+" euros"}><defs><pattern id={uid+i} width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="6" height="6" fill="#f6f7f9"/><line y2="6" stroke="#dce1e9" strokeWidth="2"/></pattern></defs><rect width="520" height="24" y="3" rx="6" fill={"url(#"+uid+i+")"}/><rect width={Number(n)/40000*520} height="24" y="3" rx="6" fill={["#ec9b55","#be72bb","#629ceb"][i]}/><rect x={Number(n)/40000*520-3} width="6" height="30" rx="3" fill="white" stroke="#aeb9c9"/></svg></div>)}<p>Échelle commune : 0 — 40 000 € · les repères indiquent la valeur.</p></div>}
 {mode==="Livraisons"&&<div className="bm-detailed-deliveries">{[["Emma",98],["Paul",78],["Alice",68],["Léa",48]].map(([name,n],i)=><div key={name} {...inspect(name+" : "+n+" livraisons à l’heure sur 100")}><div><span className="bm-detailed-avatar" style={{background:palette[i]+"22",color:palette[i]}}>{String(name)[0]}</span><strong>{name}</strong><span>100 livraisons</span><b>{n} %</b></div><div className="bm-delivery-track"><i style={{width:n+"%",background:palette[i]}}/><span style={{left:n+"%",color:palette[i]}}><Truck size={19}/></span></div></div>)}</div>}
 </>}<footer className="bm-chart-legend">{mode==="Pixels"?"Noir : finalisés · gris : en cours · fond clair : grille jusqu’à 20.":mode==="Miroir"?"Bleu : entrées · bleu pâle : sorties · même échelle autour de zéro.":mode==="Nuage"?"Vert / orange : offres comparables fictives · bleu : votre offre.":"Valeurs et unités explicites · données de démonstration."}</footer></div></section>;
}
