import {DistributionChart} from '../design-system/workshop-charts';
import { ChartTooltipArea } from "./chart-tooltip";
import { useState, useRef, useEffect } from "react";
import { detailedModes, DetailedChartVariants, type DetailedChartMode } from "./charts-variants";
import "./charts-demo.css";
export type ExtraMode = "Profondeur" | "Jauges" | "Donut" | "Heatmap" | DetailedChartMode;
const days = ["Lun", "Mar", "Mer", "Jeu", "Ven"];
export type DepthChartProps = { empty?: boolean; locale?: "fr" | "en" };
export function DepthChart({ empty = false, locale = "fr" }: DepthChartProps) {
 return <ChartsExtra mode="Profondeur" empty={empty} locale={locale}/>;
}
export function ChartsExtra({ mode, empty, locale="fr" }: { mode: ExtraMode; empty: boolean; locale?: "fr" | "en" }) {
 const plotRef=useRef<HTMLDivElement>(null);
 const [plotWidth,setPlotWidth]=useState(540);
 useEffect(()=>{const el=plotRef.current;if(!el)return;const observer=new ResizeObserver(([entry])=>setPlotWidth(Math.max(240,entry.contentRect.width)));observer.observe(el);return()=>observer.disconnect()},[]);
 const [focus, setFocus] = useState<string | null>(null);
 const [gauge, setGauge] = useState(65);
 if(mode==='Donut'&&!empty)return <DistributionChart title="Répartition des dossiers" caption="Dossiers" rows={[{label:'Services',value:44},{label:'Industrie',value:32},{label:'Technologie',value:24}]}/>;
 if (detailedModes.includes(mode as DetailedChartMode)) return <DetailedChartVariants mode={mode as DetailedChartMode} empty={empty}/>;
 const title = {Profondeur:"Capacité de traitement",Jauges:"Objectifs de qualification",Donut:"Répartition des dossiers",Heatmap:"Activité par jour et heure"}[mode as "Profondeur" | "Jauges" | "Donut" | "Heatmap"];
 return <section className="bm-chart-shell bm-extra"><header className="bm-chart-heading">{locale==="en"&&mode==="Profondeur"?"Processing capacity":title}<span className="bm-chart-date">{locale==="en"?"Illustrative week":"Données fictives · septembre 2026"}</span></header><div className="bm-chart-body" ref={plotRef}><ChartTooltipArea enabled={mode==="Profondeur"||mode==="Heatmap"}>{mode!=="Profondeur"&&mode!=="Heatmap"&&<div className="bm-extra-tip" role="status">{focus || "Survolez ou parcourez les valeurs avec Tab."}</div>}{empty ? <div className="bm-chart-empty"><strong>Aucune donnée sur cette période</strong></div> : <>
 {mode === "Profondeur" && <svg viewBox={`0 0 ${plotWidth} 220`} role="group" aria-label={locale==="en"?"Processed records, capacity 12 records per day":"Dossiers traités, capacité 12 dossiers par jour"}>
 {[0,3,6,9,12].map(v=><g key={v}><line x1="28" x2={plotWidth-8} y1={184-v*12} y2={184-v*12} stroke="#e6e9ee" strokeDasharray="3 6"/><text x="20" y={188-v*12} textAnchor="end">{v}</text></g>)}
 {[8,5,9,7,3,6].map((v,i)=>{const step=(plotWidth-42)/6,depthWidth=Math.min(34,step*.7),x=34+i*step,y=184-v*12;return <g key={i} data-chart-title={`${i+7} ${locale==="en"?"September":"septembre"} 2026`} data-chart-value={`${v} ${locale==="en"?"records processed":"dossiers traités"}`} data-chart-detail={locale==="en"?`Capacity: 12 / day · ${Math.round(v/12*100)}% used`:`Capacité : 12 / jour · ${Math.round(v/12*100)} % utilisée`} data-chart-color="var(--bm-depth-front,#e99336)" tabIndex={0} role="img" aria-label={locale==="en"?`${i+7} September: ${v} records processed of 12`:`${i+7} septembre : ${v} dossiers traités sur 12`} onFocus={()=>setFocus(`${i+7} sept. · ${v} / 12 dossiers`)} onBlur={()=>setFocus(null)} onMouseEnter={()=>setFocus(`${i+7} sept. · ${v} / 12 dossiers`)} onMouseLeave={()=>setFocus(null)} className="bm-chart-point"><path d={`M${x} 32 L${x+depthWidth/2} 40 V184 L${x} 176Z`} fill="var(--bm-depth-empty-front,#fff0e4)"/><path d={`M${x+depthWidth/2} 40 L${x+depthWidth} 32 V176 L${x+depthWidth/2} 184Z`} fill="var(--bm-depth-empty-side,#f8dfca)"/><path d={`M${x} 32 L${x+depthWidth/2} 24 L${x+depthWidth} 32 L${x+depthWidth/2} 40Z`} fill="var(--bm-depth-empty-top,#ffead9)"/><path d={`M${x} ${y-8} L${x+depthWidth/2} ${y} V184 L${x} 176Z`} fill="var(--bm-depth-front,#ff9a4d)"/><path d={`M${x+depthWidth/2} ${y} L${x+depthWidth} ${y-8} V176 L${x+depthWidth/2} 184Z`} fill="var(--bm-depth-side,#e97b30)"/><path d={`M${x} ${y-8} L${x+depthWidth/2} ${y-16} L${x+depthWidth} ${y-8} L${x+depthWidth/2} ${y}Z`} fill="var(--bm-depth-top,#ffb879)"/><path d={`M${x+depthWidth/2} ${y} V184`} stroke="var(--bm-depth-top,#ffca9d)" strokeWidth=".7"/><rect className="bm-chart-focus" x={x-3} y="19" width="50" height="170" rx="4"/><text x={x+depthWidth/2} y="207" textAnchor="middle">{i+7} Sep</text></g>})}<text x="28" y="17">{locale==="en"?"Records / day":"Dossiers / jour"}</text></svg>}
 {mode === "Jauges" && <div className="bm-gauges">{[["Dossiers qualifiés",gauge,"#5574f5"],["Pièces reçues",85,"#9954df"],["Signatures obtenues",30,"#dd6783"]].map(([label,value,color])=><div className="bm-gauge" key={label}><div><span>{label}</span><strong>{value}%</strong></div><div className="bm-gauge-track" role="meter" aria-label={String(label)} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Number(value)}>{Array.from({length:20},(_,i)=><i key={i} style={{background:i<Number(value)/5?String(color):undefined}}/>)}</div></div>)}<label className="bm-gauge-range">Qualification · pas de 5 %<input aria-label="Taux de qualification" type="range" min={0} max={100} step={5} value={gauge} onChange={e=>setGauge(Number(e.target.value))}/></label></div>}
 {mode === "Donut" && <div className="bm-donut-layout"><svg viewBox="0 0 240 240" role="group" aria-label="Répartition de 100 dossiers par secteur">{Array.from({length:50},(_,i)=>{const angle=(i*7.2-90)*Math.PI/180, color=i<22?"#277fea":i<38?"#e99336":"#9664cc";return <line key={i} x1={120+70*Math.cos(angle)} y1={120+70*Math.sin(angle)} x2={120+91*Math.cos(angle)} y2={120+91*Math.sin(angle)} stroke={color} strokeWidth="6" strokeLinecap="round"/>})}<text x="120" y="119" textAnchor="middle" className="bm-donut-total">100</text><text x="120" y="140" textAnchor="middle">dossiers</text></svg><div className="bm-donut-legend">{[["Services",44,"#277fea"],["Industrie",32,"#e99336"],["Technologie",24,"#9664cc"]].map(([label,n,c])=><button type="button" key={label} onFocus={()=>setFocus(`${label} · ${n} dossiers · ${n} %`)} onBlur={()=>setFocus(null)} onMouseEnter={()=>setFocus(`${label} · ${n} dossiers · ${n} %`)} onMouseLeave={()=>setFocus(null)}><i style={{background:String(c)}}/><span>{label}</span><strong>{n}%</strong></button>)}</div></div>}
 {mode === "Heatmap" && <div className="bm-heatmap"><div className="bm-heat-grid"><span/>{Array.from({length:8},(_,h)=><span key={h}>{h+9} h</span>)}{days.map((day,d)=><div className="bm-heat-row" key={day}><span>{day}</span>{Array.from({length:8},(_,h)=>{const n=(d*3+h*2+Math.floor(h/3))%9;const label=`${day} ${7+d} septembre, ${h+9} h : ${n} actions`;return <button key={h} data-chart-title={`${day} ${7+d} septembre · ${h+9} h`} data-chart-value={`${n} action${n===1?'':'s'}`} data-chart-detail="Activité sur ce créneau d’une heure" type="button" aria-label={label} style={{background:["#f0f4f9","#dfebf8","#c9dff6","#b0d1f3","#94bfed","#71a8e4","#528fd4","#3575ba","#1e5b9c"][n]}} onFocus={()=>setFocus(label)} onBlur={()=>setFocus(null)} onMouseEnter={()=>setFocus(label)} onMouseLeave={()=>setFocus(null)}/>;})}</div>)}</div><div className="bm-heat-key"><span>0 action</span>{["#f0f4f9","#c9dff6","#94bfed","#528fd4","#1e5b9c"].map(c=><i key={c} style={{background:c}}/>)}<span>8 actions</span></div></div>}
 </>}<footer className="bm-chart-legend">{mode === "Profondeur" ? (locale==="en"?"Processed / capacity · 12 per day · illustrative week":"Orange : traité · enveloppe pâle : capacité de 12 / jour · base à zéro.") : mode === "Jauges" ? "20 segments · chaque segment représente 5 %." : mode === "Donut" ? "50 segments · chaque segment représente 2 dossiers (2 %)." : "Actions enregistrées par créneau d’une heure · du 7 au 11 septembre."}</footer></ChartTooltipArea></div></section>;
}
