import { useState } from "react";
import "./comparison-charts.css";
import { SparklineCell } from "./rich-table-cells";
const rows=[{name:"Recommandations",first:420,last:310},{name:"Recherche",first:360,last:280},{name:"Réseaux sociaux",first:235,last:125},{name:"Contact direct",first:260,last:470},{name:"Événements",first:210,last:300}];
const companies=[{name:"Atelier Nord",values:[2,4,3,6,5,8,7],color:"#279576"},{name:"Maison Astrée",values:[7,5,6,4,5,3,2],color:"#b76b37"},{name:"Studio Rivage",values:[2,2,3,4,3,5,6],color:"#347ddd"},{name:"Alto Industrie",values:[4,5,4,5,4,5,4],color:"#8271bb"}];
export function ComparisonChartsDemo(){
 const [mode,setMode]=useState<"Attribution"|"Sparklines">("Attribution"),[active,setActive]=useState<string|null>(null),[showFirst,setShowFirst]=useState(true),[showLast,setShowLast]=useState(true),[empty,setEmpty]=useState(false);
 return <div className="bm-comparison"><div className="bm-comparison-controls"><div>{(["Attribution","Sparklines"] as const).map(m=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setActive(null)}}>{m}</button>)}</div><label><input type="checkbox" checked={empty} onChange={e=>setEmpty(e.target.checked)}/>État vide</label></div><section><header><h3>{mode==="Attribution"?"Attribution du pipeline":"Activité des sociétés"}</h3><p>{mode==="Attribution"?"Montants attribués au premier et au dernier contact.":"Actions enregistrées · du 8 au 14 septembre 2026"}</p></header>{mode==="Attribution"&&<div className="bm-comparison-legend"><button type="button" aria-pressed={showFirst} onClick={()=>setShowFirst(!showFirst)}><i/>Premier contact</button><button type="button" aria-pressed={showLast} onClick={()=>setShowLast(!showLast)}><i/>Dernier contact</button></div>}
 <div className="bm-comparison-tip" role="status" aria-live="polite">{active || (mode==="Attribution"?"Milliers d’euros · même échelle de 0 à 500 k€":"Mini-courbes · même échelle de 0 à 10 actions par jour")}</div>
 {empty?<div className="bm-comparison-empty">Aucune donnée sur cette période.</div>:mode==="Attribution"?<div className="bm-horizontal-chart"><div className="bm-horizontal-ticks"><div>{[0,100,200,300,400,500].map(v=><span key={v} style={{left:`${v/5}%`}}>{v}</span>)}</div></div>{rows.map(row=><div className="bm-horizontal-row" key={row.name}><span>{row.name}</span><div>{showFirst&&<button type="button" className="first" style={{width:`${row.first/5}%`}} aria-label={`${row.name}, premier contact : ${row.first} milliers d’euros`} onFocus={()=>setActive(`${row.name} · premier contact · ${row.first} k€`)} onBlur={()=>setActive(null)} onMouseEnter={()=>setActive(`${row.name} · premier contact · ${row.first} k€`)} onMouseLeave={()=>setActive(null)}/>} {showLast&&<button type="button" className="last" style={{width:`${row.last/5}%`}} aria-label={`${row.name}, dernier contact : ${row.last} milliers d’euros`} onFocus={()=>setActive(`${row.name} · dernier contact · ${row.last} k€`)} onBlur={()=>setActive(null)} onMouseEnter={()=>setActive(`${row.name} · dernier contact · ${row.last} k€`)} onMouseLeave={()=>setActive(null)}/>}</div></div>)}{!showFirst&&!showLast&&<p className="bm-no-series">Activez une série dans la légende.</p>}</div>:<div className="bm-spark-table"><div className="bm-spark-head"><span>Société</span><span>7 derniers jours</span><span>Total</span></div>{companies.map(company=><div className="bm-spark-row" key={company.name}><span>{company.name}</span><SparklineCell values={company.values} label={`${company.name}, actions du 8 au 14 septembre`} color={company.color} value={company.values.reduce((a,b)=>a+b,0)} onInspect={()=>setActive(`${company.name} · ${company.values.join(" / ")} actions`)} onActiveChange={isActive=>setActive(isActive?`${company.name} · ${company.values.join(" / ")} actions`:null)}/></div>)}</div>}
 <footer>{mode==="Attribution"?"Deux modèles d’attribution d’un même pipeline : les séries ne s’additionnent pas.":"Chaque courbe contient 7 jours. Le total est la somme des actions quotidiennes."}<span>Données fictives</span></footer></section></div>;
}
