import { AmountInput } from "./ui/amount-input";
import { useId, useState } from "react";
import { Box, Database, Globe2, Minus, Plus, Scan, Waypoints } from "lucide-react";
import "./dependency-graph.css";
type Node={id:string;name:string;kind:"Service"|"Données"|"Externe"|"Entrée";x:number;y:number;detail:string;status:"Opérationnel"|"Dégradé"};
const nodes:Node[]=[
{id:"gateway",name:"api-gateway",kind:"Entrée",x:22,y:118,detail:"Point d’entrée des applications",status:"Opérationnel"},
{id:"portal",name:"admin-portal",kind:"Entrée",x:22,y:328,detail:"Espace de travail des équipes",status:"Opérationnel"},
{id:"orders",name:"orders-api",kind:"Service",x:220,y:65,detail:"Lecture et mise à jour des dossiers",status:"Opérationnel"},
{id:"auth",name:"auth-service",kind:"Service",x:220,y:225,detail:"Contrôle des accès et sessions",status:"Opérationnel"},
{id:"inventory",name:"inventory-svc",kind:"Service",x:220,y:385,detail:"Index des pièces documentaires",status:"Dégradé"},
{id:"db",name:"orders-db",kind:"Données",x:420,y:65,detail:"Base des dossiers · PostgreSQL",status:"Opérationnel"},
{id:"queue",name:"events-queue",kind:"Données",x:420,y:225,detail:"File de traitement des événements",status:"Opérationnel"},
{id:"cache",name:"redis-cache",kind:"Données",x:420,y:385,detail:"Cache partagé des services",status:"Opérationnel"},
{id:"crm",name:"crm-sync",kind:"Externe",x:618,y:118,detail:"Synchronisation du CRM",status:"Opérationnel"},
{id:"mail",name:"notifications",kind:"Externe",x:618,y:328,detail:"Service de notifications",status:"Opérationnel"},
];
const edges=[{from:"gateway",to:"orders"},{from:"gateway",to:"auth"},{from:"portal",to:"orders"},{from:"portal",to:"inventory"},{from:"orders",to:"db"},{from:"orders",to:"queue",async:true},{from:"orders",to:"cache"},{from:"inventory",to:"db"},{from:"inventory",to:"cache"},{from:"auth",to:"cache"},{from:"queue",to:"mail",async:true},{from:"orders",to:"crm"}];
function connected(selected:string,direction:"Amont"|"Aval"){
 const seen=new Set([selected]),queue=[selected];
 while(queue.length){const current=queue.pop()!;for(const edge of edges){const next=direction==="Amont"?(edge.to===current?edge.from:null):(edge.from===current?edge.to:null);if(next&&!seen.has(next)){seen.add(next);queue.push(next)}}}return seen;
}
export function DependencyGraphDemo(){
 const [selected,setSelected]=useState("db"),[direction,setDirection]=useState<"Amont"|"Aval">("Amont"),[zoom,setZoom]=useState(1);
 const uid=useId().replace(/:/g,""),related=connected(selected,direction),node=nodes.find(n=>n.id===selected)!;
 const direct=edges.filter(e=>direction==="Amont"?e.to===selected:e.from===selected).map(e=>nodes.find(n=>n.id===(direction==="Amont"?e.from:e.to))!);
 return <section className="bm-dependency"><header><div><Waypoints size={16}/><h3>Graphe de dépendances</h3><span>{nodes.length} nœuds · {edges.length} liens</span></div><span className="bm-dependency-demo">Démonstration</span></header><div className="bm-dependency-toolbar"><div className="bm-graph-zoom"><button type="button" aria-label="Ajuster le graphe" onClick={()=>setZoom(1)}><Scan size={14}/></button><button type="button" aria-label="Réduire le zoom" disabled={zoom<=.75} onClick={()=>setZoom(v=>Math.max(.75,v-.25))}><Minus size={14}/></button><output aria-label="Niveau de zoom">{Math.round(zoom*100)} %</output><button type="button" aria-label="Augmenter le zoom" disabled={zoom>=2} onClick={()=>setZoom(v=>Math.min(2,v+.25))}><Plus size={14}/></button></div><div className="bm-dependency-direction">{(["Amont","Aval"] as const).map(d=><button type="button" key={d} aria-pressed={direction===d} onClick={()=>setDirection(d)}>{d}</button>)}</div><span className="bm-dependency-selection">{node.name} · {related.size-1} {direction==="Amont"?"appelants":"dépendances"}</span></div>
 <div className="bm-dependency-scroll" tabIndex={0} aria-label="Graphe défilant, sélectionnez un nœud"><svg viewBox="0 0 802 477" style={{width:`${zoom*100}%`}} role="group" aria-label="Dépendances de services de démonstration"><defs><pattern id={`${uid}-dots`} width="15" height="15" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#dce3eb"/></pattern><marker id={`${uid}-arrow`} markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="none" stroke="#c9d3df" strokeWidth="1"/></marker><marker id={`${uid}-active`} markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="none" stroke="#2584eb" strokeWidth="1"/></marker></defs><rect width="802" height="477" fill={`url(#${uid}-dots)`}/>{edges.map(edge=>{const from=nodes.find(n=>n.id===edge.from)!,to=nodes.find(n=>n.id===edge.to)!,highlight=related.has(edge.from)&&related.has(edge.to);const x=from.x+160,y=from.y+29,tx=to.x-3,ty=to.y+29;return <path key={edge.from+edge.to} d={`M${x} ${y} C${x+40} ${y},${tx-40} ${ty},${tx} ${ty}`} fill="none" stroke={highlight?"#2584eb":"#d5dde6"} strokeWidth={highlight?2:1.2} strokeDasharray={edge.async?"4 4":undefined} markerEnd={`url(#${uid}-${highlight?"active":"arrow"})`}/>})}{nodes.map(item=>{const Icon=item.kind==="Données"?Database:item.kind==="Externe"?Globe2:item.kind==="Entrée"?Waypoints:Box;return <g key={item.id} transform={`translate(${item.x},${item.y})`} role="button" tabIndex={0} aria-label={`${item.name}, ${item.kind}, ${item.status}`} aria-pressed={selected===item.id} className={`bm-dependency-node ${selected===item.id?"selected":""} ${related.has(item.id)?"related":""}`} onClick={()=>setSelected(item.id)} onKeyDown={e=>{if(e.key===" "||e.key==="Enter"){e.preventDefault();setSelected(item.id)}}}><rect width="160" height="58" rx="10"/><circle cx="23" cy="27" r="13" fill={item.kind==="Données"?"#fbeef9":item.kind==="Externe"?"#fff5df":"#edf5ff"}/><Icon x={15} y={19} width={16} height={16} strokeWidth={1.5} color={item.kind==="Données"?"#b963ad":item.kind==="Externe"?"#a98237":"#5387c8"}/><text x="43" y="26" className="bm-dependency-name">{item.name}</text><text x="43" y="41">{item.kind}</text><circle cx="153" cy="5" r="3.6" fill={item.status==="Dégradé"?"#dba437":"#47ad83"} stroke="white" strokeWidth="2"/></g>})}</svg></div>
 <div className="bm-dependency-details" aria-live="polite"><div><strong>{node.name}</strong><span>{node.detail}</span><small className={node.status==="Dégradé"?"warn":""}>{node.status}</small></div><div><span>{direction==="Amont"?"Appelants directs":"Dépendances directes"}</span>{direct.length?direct.map(n=><button type="button" key={n.id} onClick={()=>setSelected(n.id)}>{n.name}</button>):<small>Aucun lien direct dans cette direction</small>}</div></div><footer><span><i/>Opérationnel</span><span><i className="warn"/>Dégradé</span><span><b/>Appel synchrone</span><span><b className="async"/>Événement asynchrone</span><span><b className="selected"/>Chemin sélectionné</span></footer></section>;
}

export function ConditionalWorkflowDemo(){
 const [conditional,setConditional]=useState(false),[amount,setAmount]=useState('2400'),[threshold,setThreshold]=useState('1000'),[result,setResult]=useState<boolean|null>(null);
 const valid=Number.isFinite(Number(amount))&&Number(amount)>=0&&Number(amount)<=1000000&&amount.trim()!==''&&(!conditional||(Number.isFinite(Number(threshold))&&Number(threshold)>=0&&threshold.trim()!==''));
 return <section className="bm-dependency bm-conditional"><header><div><Waypoints size={16}/><h3>Validation d’un devis</h3></div><span className="bm-dependency-demo">Simulation locale</span></header><div className="bm-condition-controls"><label>Montant du devis<AmountInput  min="0" max="1000000" value={amount} onValueChange={e=>{setAmount(e);setResult(null)}}/>€</label><button type="button" disabled={!valid} onClick={()=>setResult(!conditional||Number(amount)>=Number(threshold))}>Tester le scénario</button></div><div className="bm-condition-scroll"><div className="bm-condition-canvas"><svg viewBox="0 0 850 420" aria-hidden="true"><path d="M253 106 C290 106,280 160,314 160"/><path d="M444 216 V278"/><path d={conditional?'M574 326 C620 326,612 160,644 160':'M574 160 H644'} className={result===true?'active':''}/>{conditional&&<circle cx="444" cy="216" r="3"/>}</svg><span className="bm-condition-start">Départ</span><article className="bm-condition-node intro"><header><Box size={15}/>Informations</header><div><span className="bm-condition-tag">Devis</span><strong>Nouveau devis reçu</strong><p>Dossier Atlas · {Number(amount).toLocaleString('fr-FR')} €</p></div></article><article className="bm-condition-node trigger"><header><Waypoints size={15}/>Quand</header><div><strong>Un devis est créé</strong></div><i className="port left"/><i className="port right"/><i className="port bottom"/></article><div className="bm-onlyif">Seulement si</div>{conditional?<article className="bm-condition-node condition"><header>Condition<button type="button" aria-label="Retirer la condition" onClick={()=>{setConditional(false);setResult(null)}}>×</button></header><div><label>Montant supérieur ou égal à<span><AmountInput  min="0" value={threshold} onValueChange={e=>{setThreshold(e);setResult(null)}} aria-label="Seuil de validation en euros"/> €</span></label></div></article>:<button type="button" className="bm-condition-add" onClick={()=>{setConditional(true);setResult(null)}}><Plus size={15}/>Ajouter une condition</button>}<article className={`bm-condition-node action ${result===true?'passed':''}`}><header><Box size={15}/>Alors</header><div><strong>Préparer la validation</strong><p>{result===null?'En attente du test':result?'Action simulée':'Action ignorée'}</p></div><i className="port left"/></article></div></div><div className="bm-condition-result" role="status">{result===null?'Ajoutez une condition, réglez les montants puis testez.':result?'Le devis respecte les conditions. La préparation de validation a été simulée.':'Montant inférieur au seuil : aucune action déclenchée.'}</div><footer>Aucun devis réel créé · aucun message envoyé · règles et données de démonstration</footer></section>;
}
