import { DataTable, DataRow } from "./ui/data-table";
import {useState} from "react";
import {candles,asks,bids} from "./financial-model.mjs";
import "./specialist-charts.css";
type Candle={day:number;open:number;close:number;high:number;low:number;volume:number};
type Order={price:number;size:number;total:number};
const modes=["Chandeliers","Carnet d’ordres","Profondeur","Aires empilées","Composite"] as const;
export function FinancialChartsDemo(){
 const [mode,setMode]=useState<typeof modes[number]>("Chandeliers"),[tip,setTip]=useState(""),[empty,setEmpty]=useState(false);
 const inspect=(s:string)=>({tabIndex:0,onFocus:()=>setTip(s),onBlur:()=>setTip(""),onMouseEnter:()=>setTip(s),onMouseLeave:()=>setTip("")});
 const y=(n:number)=>220-(n-95)*7;
 const seriesA=[22,34,27,39,32,45,38,49],seriesB=[12,18,16,14,20,17,22,18];
 return <div className="bm-specialist"><div className="bm-specialist-controls">{modes.map(m=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setTip("")}}>{m}</button>)}<label><input type="checkbox" checked={empty} onChange={e=>setEmpty(e.target.checked)}/>État vide</label></div><section className="bm-specialist-card dark"><header><strong>{mode}</strong><span>Actif DÉMO · données fictives</span></header><div className="bm-specialist-tip" role="status">{tip||"Explorez les valeurs au survol ou avec Tab."}</div>{empty?<div className="bm-specialist-empty">Aucune observation sur cette période.</div>:<>
 {mode==="Chandeliers"&&<svg viewBox="0 0 640 365" role="group" aria-label="Cours quotidien et volume échangé pour vingt jours"><text x="40" y="18">Prix · €</text>{[95,100,105,110,115,120].map(n=><g key={n}><line x1="42" x2="608" y1={y(n)} y2={y(n)} className="grid"/><text x="30" y={y(n)+4} textAnchor="end">{n}</text></g>)}{(candles as Candle[]).map((c,i)=><g key={c.day} {...inspect("Jour "+c.day+" · ouverture "+c.open+" €, haut "+c.high+" €, bas "+c.low+" €, clôture "+c.close+" €, volume "+c.volume+" unités")}><line x1={54+i*28} x2={54+i*28} y1={y(c.high)} y2={y(c.low)} stroke={c.close>=c.open?"#72c9a4":"#e89199"}/><rect x={47+i*28} y={y(Math.max(c.open,c.close))} width="14" height={Math.max(2,Math.abs(c.close-c.open)*7)} fill={c.close>=c.open?"#72c9a4":"#e89199"} rx="1"/><rect x={47+i*28} y={320-c.volume*.12} width="14" height={c.volume*.12} fill={c.close>=c.open?"#72c9a4":"#e89199"} opacity=".7"/>{i%3===0&&<text x={54+i*28} y="344" textAnchor="middle">J{c.day}</text>}</g>)}<text x="42" y="248">Volume · unités</text>{[0,250,500].map(n=><text key={n} x="30" y={324-n*.12} textAnchor="end">{n}</text>)}</svg>}
 {mode==="Carnet d’ordres"&&<div className="bm-orderbook"><DataTable sortable={false}><caption>Carnet instantané fictif · unités cumulées depuis le meilleur prix</caption><thead><DataRow><th>Prix (€)</th><th>Quantité</th><th>Cumul</th></DataRow></thead><tbody>{[...(asks as Order[])].reverse().map(o=><DataRow key={o.price} {...inspect("Vente "+o.price+" € · "+o.size+" unités · cumul "+o.total)} className="ask" style={{background:"linear-gradient(to left, #6c353f55 "+o.total/10+"%,transparent "+o.total/10+"%)"}}><td>{o.price.toFixed(2)}</td><td>{o.size}</td><td>{o.total}</td></DataRow>)}<DataRow className="bm-order-spread"><td colSpan={3}>Milieu 100,50 € <span>Écart achat / vente : 1,00 €</span></td></DataRow>{(bids as Order[]).map(o=><DataRow key={o.price} {...inspect("Achat "+o.price+" € · "+o.size+" unités · cumul "+o.total)} className="bid" style={{background:"linear-gradient(to left, #32604d55 "+o.total/10+"%,transparent "+o.total/10+"%)"}}><td>{o.price.toFixed(2)}</td><td>{o.size}</td><td>{o.total}</td></DataRow>)}</tbody></DataTable></div>}
 {mode==="Profondeur"&&<svg viewBox="0 0 640 300" role="group" aria-label="Volume cumulé des achats et ventes par niveau de prix"><text x="42" y="18">Volume cumulé · unités</text>{[0,250,500,750,1000].map(n=><g key={n}><line x1="50" x2="600" y1={250-n*.2} y2={250-n*.2} className="grid"/><text x="37" y={254-n*.2} textAnchor="end">{n}</text></g>)}{[bids,asks].map((rows,index)=>{const sorted=[...(rows as Order[])].sort((a,b)=>a.price-b.price),x=(price:number)=>50+(price-95)*50;let path="M"+x(sorted[0].price)+" 250 L"+x(sorted[0].price)+" "+(250-sorted[0].total*.2);sorted.slice(1).forEach(o=>{path+=" H"+x(o.price)+" V"+(250-o.total*.2)});path+=" L"+x(sorted[sorted.length-1].price)+" 250Z";return <g key={index}><path d={path} fill={index?"#e8919933":"#72c9a433"} stroke={index?"#e89199":"#72c9a4"}/>{sorted.map(o=><circle key={o.price} cx={x(o.price)} cy={250-o.total*.2} r="4" fill={index?"#e89199":"#72c9a4"} {...inspect((index?"Ventes":"Achats")+" à "+o.price+" € : "+o.total+" unités cumulées")}/>)}</g>})}{[95,97,99,101,103,105,106].map(n=><text key={n} x={50+(n-95)*50} y="273" textAnchor="middle">{n}</text>)}<text x="600" y="295" textAnchor="end">Prix · €</text></svg>}
 {(mode==="Aires empilées"||mode==="Composite")&&<svg viewBox="0 0 640 305" role="group" aria-label={mode==="Composite"?"Barres en dossiers et courbe en pourcentage, deux axes explicitement distincts":"Aires empilées par canal, même unité et base zéro"}><text x="42" y="18">Dossiers</text>{[0,20,40,60,80].map(n=><g key={n}><line x1="46" x2="582" y1={250-n*2.5} y2={250-n*2.5} className="grid"/><text x="33" y={254-n*2.5} textAnchor="end">{n}</text>{mode==="Composite"&&<text x="596" y={254-n*2.5}>{n/80*100}%</text>}</g>)}{mode==="Aires empilées"?<><path d={"M50 250 L"+seriesA.map((n,i)=>(50+i*75)+" "+(250-n*2.5)).join(" L")+" L575 250Z"} fill="#6e9ce3" opacity=".7"/><path d={"M"+seriesA.map((n,i)=>(50+i*75)+" "+(250-(n+seriesB[i])*2.5)).join(" L")+" L"+[...seriesA].reverse().map((n,i)=>(575-i*75)+" "+(250-n*2.5)).join(" L")+"Z"} fill="#e6c366" opacity=".8"/></>:<>{seriesA.map((n,i)=><rect key={i} x={36+i*75} y={250-n*2.5} width="28" height={n*2.5} fill="#6e9ce3" opacity=".65"/>)}<polyline points={seriesB.map((n,i)=>(50+i*75)+","+(250-n*4*2)).join(" ")} fill="none" stroke="#e6c366" strokeWidth="2.5"/><text x="590" y="18" textAnchor="end">Conversion · %</text></>}{seriesA.map((n,i)=><g key={i} {...inspect("Semaine "+(i+1)+" : "+n+" dossiers"+(mode==="Composite"?", conversion "+seriesB[i]*4+" %":", second canal "+seriesB[i]+" dossiers, total "+(n+seriesB[i])))}><rect x={32+i*75} y="40" width="36" height="213" fill="transparent"/><text x={50+i*75} y="276" textAnchor="middle">S{i+1}</text></g>)}</svg>}
 </>}<footer>{mode==="Chandeliers"?"Vert : clôture ≥ ouverture · rose : clôture < ouverture. Mèches = extrêmes.":"Démonstration locale · aucune cotation ni donnée de marché réelle."}{mode==="Aires empilées"&&" Bleu : direct · jaune : partenaires."}{mode==="Composite"&&" Bleu : dossiers (gauche) · jaune : conversion (droite)."}</footer></section></div>;
}
