import { AppSelect } from "./ui/app-select";
import { useId, useState } from "react";
import countries from "./map-countries.json";
import "./map-demo.css";
const coverage:Record<string,{label:string;count:number}>={"250":{label:"France",count:38},"276":{label:"Allemagne",count:24},"840":{label:"États-Unis",count:42},"076":{label:"Brésil",count:16},"036":{label:"Australie",count:12},"356":{label:"Inde",count:27},"826":{label:"Royaume-Uni",count:31},"724":{label:"Espagne",count:19}};
export function MapDemo(){
 const uid=useId().replace(/:/g,""),[selected,setSelected]=useState("250"),[empty,setEmpty]=useState(false);
 const country=countries.find(c=>c.id===selected),value=coverage[selected];
 return <section className="bm-map"><header><div><h3>Présence internationale</h3><p>{empty?"0":Object.keys(coverage).length} pays avec des dossiers · données fictives</p></div><label><input type="checkbox" checked={empty} onChange={e=>setEmpty(e.target.checked)}/>État vide</label></header><div className="bm-map-toolbar"><label>Pays<AppSelect value={selected} onValueChange={e=>setSelected(e)}>{[...countries].sort((a,b)=>a.name.localeCompare(b.name)).map(c=><option key={c.id} value={c.id}>{coverage[c.id]?.label??c.name}</option>)}</AppSelect></label><div><span><i/>Avec dossiers</span><span><i/>Sans donnée</span></div></div>
 <svg viewBox="0 0 720 373" role="group" aria-label="Carte des pays, géométrie Natural Earth et projection Equal Earth"><defs><pattern id={`${uid}-base`} width="4" height="4" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1.2" fill="#8999ab"/></pattern><pattern id={`${uid}-active`} width="4" height="4" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1.45" fill="#176dcc"/></pattern></defs>{countries.map(c=><path key={c.id} d={c.path??undefined} fill={`url(#${uid}-${!empty&&coverage[c.id]?"active":"base"})`} stroke={selected===c.id?"#084b98":"transparent"} strokeWidth="1.6" role="button" tabIndex={!empty&&coverage[c.id]?0:-1} aria-label={`${coverage[c.id]?.label??c.name} : ${!empty&&coverage[c.id]?`${coverage[c.id].count} dossiers fictifs`:"aucune donnée"}`} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)} onFocus={()=>setSelected(c.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(c.id)}}}/>)}</svg>
 <div className="bm-map-selected" role="status" aria-live="polite"><span>{value?.label??country?.name}</span><strong>{!empty&&value?`${value.count} dossiers`:"Aucune donnée"}</strong><span>{!empty&&value?"Exemple de couverture commerciale":"Aucun dossier de démonstration pour ce pays"}</span></div><footer>Géométrie : <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth</a> · source world-atlas 2.0.2 · chiffres fictifs.</footer></section>;
}
