import {useState} from "react";
import "./specialist-charts.css";
const modes=["Distribution","Bulles","Arbre","Radial","Deux panneaux"] as const;
const categories=["Éditeur","Documents","Automatisation","Recherche","Intégrations"];
const nodes=[{name:"Éditeur",children:["Blocs","Tables","Commentaires"]},{name:"Automatiser",children:["Workflows","Déclencheurs","Webhooks"]},{name:"Collaborer",children:["Espaces","Invités","Mentions"]},{name:"Intégrer",children:["API","Connecteurs","Exports"]}];
export function StatisticalChartsDemo(){
 const [mode,setMode]=useState<typeof modes[number]>("Distribution"),[tip,setTip]=useState(""),[selected,setSelected]=useState<number|null>(null),[empty,setEmpty]=useState(false);
 const inspect=(s:string)=>({tabIndex:0,onFocus:()=>setTip(s),onBlur:()=>setTip(""),onMouseEnter:()=>setTip(s),onMouseLeave:()=>setTip("")});
 return <div className="bm-specialist"><div className="bm-specialist-controls">{modes.map(m=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setTip("");setSelected(null)}}>{m}</button>)}<label><input type="checkbox" checked={empty} onChange={e=>setEmpty(e.target.checked)}/>État vide</label></div><section className="bm-specialist-card"><header><strong>{mode}</strong><span>Observations fictives · 2026</span></header><div className="bm-specialist-tip" role="status">{tip||"Chaque observation se consulte au survol ou avec Tab."}</div>{empty?<div className="bm-specialist-empty">Aucune observation sur cette période.</div>:<>
 {mode==="Distribution"&&<svg viewBox="0 0 650 320" role="group" aria-label="Distribution des temps de réponse par priorité, chaque point représente un ticket"><text x="110" y="19">Temps de réponse · minutes</text>{[0,10,20,30,40,50].map(n=><g key={n}><line x1={110+n*9.5} x2={110+n*9.5} y1="30" y2="272" className="grid"/><text x={110+n*9.5} y="295" textAnchor="middle">{n}</text></g>)}{["Urgente","Normale","Faible"].map((name,r)=><g key={name}><text x="94" y={84+r*83} textAnchor="end">{name}</text>{Array.from({length:32},(_,i)=>{const minutes=3+r*9+(i*7%23),jitter=((i*11)%21)-10;return <circle key={i} cx={110+minutes*9.5} cy={80+r*83+jitter} r="3.4" fill={["#466b47","#8e9d59","#c3ad56"][r]} opacity=".7" {...inspect(name+" · ticket "+(i+1)+" · "+minutes+" minutes")}/>})}</g>)}</svg>}
 {mode==="Bulles"&&<svg viewBox="0 0 650 355" role="group" aria-label="Nombre de tickets par année et produit, aire des bulles proportionnelle au volume"><text x="72" y="15">Aire : tickets · noyau : escalades · pointillé : produit en bêta</text>{categories.map((name,c)=><text key={name} x={132+c*109} y="42" textAnchor="middle">{name}</text>)}{[2022,2023,2024,2025,2026].map((year,r)=><g key={year}><line x1="72" x2="610" y1={85+r*56} y2={85+r*56} className="grid"/><text x="56" y={89+r*56} textAnchor="end">{year}</text>{categories.map((name,c)=>{const n=16+((r*17+c*13)%65),escalations=Math.floor(n*.12),x=132+c*109,y=85+r*56,beta=c===4&&r<2;return <g key={name} {...inspect(name+" "+year+" : "+n+" tickets, "+escalations+" escalades"+(beta?", produit bêta":""))}><circle cx={x} cy={y} r={Math.sqrt(n)*2.7} fill={c===1?"#eeb9ae66":"#c2c9be55"} stroke={c===1?"#cc897c":"#9ea89a"} strokeDasharray={beta?"3 3":undefined}/><circle cx={x} cy={y} r={Math.sqrt(escalations)*2.7} fill={c===1?"#cc897c":"#697861"} opacity=".75"/></g>})}</g>)}</svg>}
 {mode==="Arbre"&&<><svg viewBox="0 0 650 365" role="group" aria-label="Arbre des capacités de la plateforme"><text x="18" y="182">Plateforme</text><circle cx="96" cy="177" r="4" fill="#394639"/>{nodes.map((node,i)=>{const y=45+i*90,active=selected===null||selected===i,color=selected===i?"#ce7667":"#889782";return <g key={node.name} opacity={active?1:.24}><path d={"M96 177 C156 177,165 "+y+",235 "+y} fill="none" stroke={color} strokeWidth="1.5"/><g role="button" aria-label={"Isoler la branche "+node.name} aria-pressed={selected===i} tabIndex={0} onClick={()=>setSelected(selected===i?null:i)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(selected===i?null:i)}}}><circle cx="235" cy={y} r="5" fill={color}/><rect x="211" y={y-23} width="112" height="40" fill="transparent"/><text x="224" y={y-12}>{node.name}</text></g>{node.children.map((leaf,j)=>{const ly=y+(j-1)*25;return <g key={leaf} {...inspect("Plateforme → "+node.name+" → "+leaf)}><path d={"M235 "+y+" C325 "+y+",335 "+ly+",430 "+ly} fill="none" stroke={color}/><circle cx="430" cy={ly} r="3.5" fill={color}/><text x="443" y={ly+4}>{leaf}</text></g>})}</g>})}</svg><p className="bm-stat-note">Entrée ou clic sur une branche pour l’isoler ; une seconde fois pour tout afficher.</p></>}
 {mode==="Radial"&&<svg viewBox="0 0 650 330" role="group" aria-label="Parts d’usage et durée moyenne par fonctionnalité"><text x="320" y="17" textAnchor="middle">Angle : part d’usage · rayon : durée moyenne</text>{[15,30,45].map(n=><circle key={n} cx="320" cy="173" r={n*2.2} fill="none" stroke="#e0e5dd" strokeDasharray="3 4"/>)}{(()=>{let start=-Math.PI/2;return [{name:"Éditeur",share:34,minutes:42},{name:"Documents",share:26,minutes:35},{name:"Recherche",share:22,minutes:28},{name:"Autres",share:18,minutes:18}].map((v,i)=>{const end=start+v.share/100*Math.PI*2,mid=(start+end)/2,r=v.minutes*2.2,inner=25,a=start+.025,b=end-.025,path="M"+(320+inner*Math.cos(a))+" "+(173+inner*Math.sin(a))+" L"+(320+r*Math.cos(a))+" "+(173+r*Math.sin(a))+" A"+r+" "+r+" 0 "+(b-a>Math.PI?1:0)+" 1 "+(320+r*Math.cos(b))+" "+(173+r*Math.sin(b))+" L"+(320+inner*Math.cos(b))+" "+(173+inner*Math.sin(b))+" A"+inner+" "+inner+" 0 0 0 "+(320+inner*Math.cos(a))+" "+(173+inner*Math.sin(a))+"Z";start=end;return <g key={v.name} {...inspect(v.name+" : "+v.share+" % de l’usage, durée moyenne "+v.minutes+" minutes")}><path d={path} fill={["#476644","#7a8f51","#a5af70","#cbd0af"][i]}/><text x={320+140*Math.cos(mid)} y={177+125*Math.sin(mid)} textAnchor={Math.cos(mid)>0?"start":"end"}>{v.name} · {v.share}% · {v.minutes} min</text></g>})})()}<text x="320" y="308" textAnchor="middle">Anneaux : 15 / 30 / 45 minutes · les surfaces ne représentent pas la part.</text></svg>}
 {mode==="Deux panneaux"&&<svg viewBox="0 0 650 365" role="group" aria-label="Dépenses publicitaires en haut, inscriptions en bas, deux échelles séparées"><text x="55" y="15">Dépenses · k€ (croissant vers le bas)</text>{[0,5,10,15].map(n=><g key={n}><line x1="55" x2="615" y1={35+n*6} y2={35+n*6} className="grid"/><text x="41" y={39+n*6} textAnchor="end">{n}</text></g>)}{Array.from({length:20},(_,i)=>{const spend=2+(i*7)%14,signups=30+i*3+(i%3)*4;return <g key={i} {...inspect("Jour "+(i+1)+" : "+spend+" k€ dépensés, "+signups+" inscriptions")}><rect x={59+i*28} y="35" width="9" height={spend*6} rx="3" fill={i===10||i===17?"#ce7667":"#9b9d94"}/><circle cx={63+i*28} cy={318-signups} r="3" fill="#657d55"/></g>})}<text x="55" y="178">Inscriptions · nombre</text>{[0,25,50,75,100].map(n=><g key={n}><line x1="55" x2="615" y1={318-n} y2={318-n} className="grid"/><text x="41" y={322-n} textAnchor="end">{n}</text></g>)}<polyline points={Array.from({length:20},(_,i)=>(63+i*28)+","+(318-(30+i*3+(i%3)*4))).join(" ")} fill="none" stroke="#657d55" strokeWidth="2"/>{[0,4,9,14,19].map(i=><text key={i} x={63+i*28} y="345" textAnchor="middle">J{i+1}</text>)}</svg>}
 </>}<footer>{mode==="Distribution"?"Décalage vertical décoratif déterministe : seule la position horizontale mesure le temps. 32 tickets par priorité.":mode==="Bulles"?"Même échelle d’aire pour toutes les bulles. Les escalades font partie des tickets.":mode==="Deux panneaux"?"Comparaison descriptive de deux séries ; aucune causalité n’est déduite.":"Données de démonstration · aucune observation réelle."}</footer></section></div>;
}
