import {useState,type ReactNode} from 'react';
import {AlertTriangle,Check,ChevronDown,FileCheck2} from 'lucide-react';
import {AnimatedReveal} from './ui/animated-reveal';
import './work-cards-demo.css';

export type InboxWorkItem={id:string;title:string;description:string;author:string;initials:string;meta:string;priority?:string;context?:string;reason?:string;photoUrl?:string;photoPosition?:string};
export type WorkInboxProps={title?:string;items:InboxWorkItem[];onOpen:(id:string)=>void;onDone:(id:string)=>void;wide?:boolean;locale?:"fr"|"en"};
export function WorkInbox({title='À traiter aujourd’hui',items,onOpen,onDone,wide=false,locale="fr"}:WorkInboxProps){const [expanded,setExpanded]=useState<string|null>(items[0]?.id??null);return <div className={`wc-demo${wide?' wc-demo-wide':''}`}><div className="wc-topline"><span>{title}</span><span>{items.length} {locale==='en'?'actions':'dossiers'}</span></div><div className="wc-demo-list">{items.map(item=><article className="wc-envelope" key={item.id}><header><span className="wc-person" aria-hidden="true" style={item.photoUrl?{backgroundImage:`url(${item.photoUrl})`,backgroundSize:'300% 100%',backgroundPosition:item.photoPosition}:undefined}>{!item.photoUrl&&item.initials}</span><strong>{item.author}</strong>{item.priority&&<span className="wc-priority">{item.priority}</span>}<time>{item.meta}</time><button aria-label={expanded===item.id?(locale==='en'?'Collapse action':'Réduire le dossier'):(locale==='en'?'Expand action':'Développer le dossier')} aria-expanded={expanded===item.id} onClick={()=>setExpanded(expanded===item.id?null:item.id)}><ChevronDown size={14} style={{transform:expanded===item.id?'none':'rotate(-90deg)'}}/></button></header><div className="wc-inner">{item.context&&<span className="wc-context">{item.context}</span>}<h3>{item.title}</h3><p>{item.description}</p><AnimatedReveal open={expanded===item.id}><>{item.reason&&<p className="wc-reason">{item.reason}</p>}<footer><button className="wc-primary" onClick={()=>onOpen(item.id)}><FileCheck2 size={13}/>{locale==='en'?'Open':'Ouvrir'}</button><button onClick={()=>onDone(item.id)}><Check size={13}/>{locale==='en'?'Mark done':'Marquer terminé'}</button></footer></></AnimatedReveal></div></article>)}</div></div>}

export type AlertLevel='neutre'|'attention'|'critique'|'aucun';
export function AlertSurface({level,title,value,action,detail,layout='card'}:{level:AlertLevel;title:string;value:ReactNode;action:ReactNode;detail:string;layout?:'card'|'banner'}){
 if(layout==='banner')return <section className={`wc-alert wc-alert-${level} wc-alert-banner`}><div className="wc-alert-banner-copy"><header>{level==='aucun'?<Check size={17}/>:<AlertTriangle size={17}/>}<span>{title}</span></header><strong>{value}</strong>{detail&&<p>{detail}</p>}</div>{action&&<div className="wc-alert-banner-action">{action}</div>}</section>;
 return <div className={`wc-alert wc-alert-${level}`}><header>{level==='aucun'?<Check size={17}/>:<AlertTriangle size={17}/>}<span>{title}</span></header><div className="wc-alert-body"><strong>{value}</strong><p>{typeof action==='string'?<b>{action}</b>:action} {detail}</p></div></div>
}
