from pathlib import Path
import json,re,html
root=Path(__file__).resolve().parents[1]
s=(root/'src/App.tsx').read_text().split('type Review')[0]
entries=[]
for obj in re.findall(r'\{[^{}]+?\}',s,re.S):
 def field(name):
  m=re.search(r'"?'+name+r'"?\s*:\s*"([^"]+)"',obj);return m.group(1) if m else ''
 if field('id') and field('title'):entries.append({k:field(k) for k in ['id','title','group','link']})
observed=json.loads((root/'inventory/observed-components.json').read_text())
rows=''.join('<a class="component" href="index.html#'+html.escape(e['id'])+'"><small>'+html.escape(e['group'])+'</small><strong>'+html.escape(e['title'])+'</strong><span>Ouvrir le composant ↗</span></a>' for e in entries)
audit=html.escape((root/'inventory/audit-n-z.md').read_text()+'\n\n'+(root/'inventory/graph-variants-sources.md').read_text())
inspections=''.join('<details><summary>'+html.escape(i['media'].split('/')[-2]+'/'+i['media'].split('/')[-1])+'</summary><a href="../../'+html.escape(i['media'].removeprefix('../'))+'">Voir la source ↗</a><p>'+html.escape(' · '.join(i['observedComponents']))+'</p><p class="muted">'+html.escape(' · '.join(i.get('remainingGaps',[])))+'</p></details>' for i in observed['inspections'])
page='''<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Couverture des composants · BM</title><style>*{box-sizing:border-box}body{margin:0;background:#fafafa;color:#292c32;font:14px/1.6 system-ui}main{max-width:1140px;margin:60px auto;padding:24px}a{color:inherit}header>a{color:#64728a}h1{font-size:32px;letter-spacing:-1px;margin-bottom:8px}p{max-width:850px}.muted,small{color:#737a85}input{font:inherit;padding:13px 16px;border:1px solid #ddd;border-radius:9px;width:100%;margin:24px 0}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(235px,1fr));gap:10px}.component{display:flex;flex-direction:column;gap:8px;background:white;padding:20px;border:1px solid #e3e5e8;border-radius:10px;text-decoration:none}.component:hover{border-color:#8ba7ce}.component span{font-size:11px;color:#6e7f97}details{background:white;border:1px solid #e5e7eb;border-radius:8px;padding:14px;margin:6px 0}summary{cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.8 system-ui;padding:20px;background:white;border:1px solid #ddd}h2{margin-top:42px}</style><main><header><a href="index.html">← Atelier</a><h1>Couverture des références</h1><p>Une entrée consultable pour chaque construction identifiée. Les variantes sont regroupées quand elles partagent leur structure, mais leurs interactions restent essayables.</p><p class="muted">État de travail : <b>COUNT entrées implémentées</b>. La présence de code ne vaut ni PASS visuel ni validation d’Arthur. L’audit du corpus et la vérification des animations restent en cours.</p></header><input type="search" aria-label="Rechercher un composant" placeholder="Rechercher un composant ou une famille…"><div class="grid">ROWS</div><h2>Sources décomposées — audit A–M et familles initiales</h2><p class="muted">SNAP sources effectivement inspectées dans ce registre. Les écarts ci-dessous sont un instantané pendant le développement ; certains ont depuis leur composant dans la grille.</p>INSPECTIONS<h2>Audit complémentaire N–Z et variantes</h2><p class="muted">Écarts constatés et limites d’observation, conservés explicitement jusqu’à la vérification.</p><pre>AUDIT</pre></main><script>document.querySelector('input').addEventListener('input',e=>{for(const card of document.querySelectorAll('.component'))card.hidden=!card.textContent.toLowerCase().includes(e.target.value.toLowerCase())});</script><style>.component[hidden]{display:none}</style></html>'''
for k,v in {'COUNT':str(len(entries)),'ROWS':rows,'SNAP':str(len(observed['inspections'])),'INSPECTIONS':inspections,'AUDIT':audit}.items():page=page.replace(k,v)
(root/'public/coverage.html').write_text(page)
print(f'Coverage: {len(entries)} components, {len(observed["inspections"])} source inspections')
