import { useRef, useState, type AriaAttributes } from 'react';
import * as Popover from '@radix-ui/react-popover';
import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react';
import { calendarDays,dateKey,parseDate } from '../input-model.mjs';
import './date-picker.css';
const months=Array.from({length:12},(_,month)=>new Date(2026,month,1).toLocaleDateString('fr-FR',{month:'long'}));
export function DatePicker({value,onValueChange,required,...aria}:AriaAttributes & {value:string;onValueChange:(value:string)=>void;required?:boolean}){
 const today=new Date(),selected=parseDate(value),initial=selected??today;
 const [open,setOpen]=useState(false),[view,setView]=useState(initial),[focus,setFocus]=useState(dateKey(initial)),[mode,setMode]=useState<'days'|'months'>('days');
 const [invalid,setInvalid]=useState(false);
 const [container,setContainer]=useState<HTMLElement|null>(null);
 const trigger=useRef<HTMLButtonElement>(null),buttons=useRef(new Map<string,HTMLButtonElement>());
 const choose=(date:Date)=>{setInvalid(false);onValueChange(dateKey(date));setOpen(false)};
 const jump=(days:number)=>{const date=new Date(today.getFullYear(),today.getMonth(),today.getDate()+days,12);choose(date)};
 const move=(delta:number)=>{const next=new Date(view.getFullYear()+(mode==='months'?delta:0),view.getMonth()+(mode==='days'?delta:0),1,12);setView(next);setFocus(dateKey(next))};
 return <><Popover.Root open={open} onOpenChange={next=>{setOpen(next);if(next){setContainer(trigger.current?.closest('dialog')??null);setView(selected??today);setFocus(dateKey(selected??today));setMode('days')}}}><Popover.Trigger asChild><button ref={trigger} type="button" className="date-field" aria-required={required} aria-invalid={invalid || undefined} {...aria}><CalendarDays size={15}/><span>{selected?selected.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}):'Choisir une date'}</span><ChevronRight size={13}/></button></Popover.Trigger><Popover.Portal container={container}><Popover.Content className="date-picker" align="start" sideOffset={7} collisionPadding={12} aria-label="Choisir une date" onOpenAutoFocus={e=>{e.preventDefault();buttons.current.get(dateKey(selected??today))?.focus()}}>
 <div className="date-picker-heading"><span>CALENDRIER</span><small>{selected?'Date sélectionnée':'Planifier une date'}</small></div>
 <div className="date-picker-nav"><button type="button" aria-label={mode==='days'?'Mois précédent':'Année précédente'} onClick={()=>move(-1)}><ChevronLeft size={15}/></button><button type="button" className="date-picker-period" onClick={()=>setMode(mode==='days'?'months':'days')}>{mode==='days'?months[view.getMonth()]+' ':''}{view.getFullYear()}</button><button type="button" aria-label={mode==='days'?'Mois suivant':'Année suivante'} onClick={()=>move(1)}><ChevronRight size={15}/></button></div>
 {mode==='months'?<div className="date-picker-months">{months.map((month,index)=><button type="button" key={month} onClick={()=>{const next=new Date(view.getFullYear(),index,1,12);setView(next);setFocus(dateKey(next));setMode('days')}}>{month.slice(0,3)}.</button>)}</div>:<><div className="date-picker-week" aria-hidden="true">{['L','M','M','J','V','S','D'].map((d,i)=><span key={i}>{d}</span>)}</div><div className="date-picker-grid" role="grid" aria-label={months[view.getMonth()]+' '+view.getFullYear()}>{Array.from({length:Math.ceil(((new Date(view.getFullYear(),view.getMonth(),1).getDay()+6)%7+new Date(view.getFullYear(),view.getMonth()+1,0).getDate())/7)},(_,week)=><div role="row" key={week}>{calendarDays(view.getFullYear(),view.getMonth()).slice(week*7,week*7+7).map(date=>{const key=dateKey(date);return <div role="gridcell" key={key} aria-selected={key===value}><button type="button" ref={el=>{if(el)buttons.current.set(key,el);else buttons.current.delete(key)}} tabIndex={key===focus?0:-1} className={`${date.getMonth()!==view.getMonth()?'outside ':''}${key===value?'selected ':''}${key===dateKey(today)?'today':''}`} aria-label={date.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} aria-current={key===dateKey(today)?'date':undefined} onClick={()=>choose(date)} onKeyDown={e=>{const delta=({ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7,Home:-(date.getDay()+6)%7,End:6-(date.getDay()+6)%7} as Record<string,number>)[e.key];if(delta===undefined&&e.key!=='PageUp'&&e.key!=='PageDown')return;e.preventDefault();const next=new Date(date);if(delta!==undefined)next.setDate(next.getDate()+delta);else next.setMonth(next.getMonth()+(e.key==='PageUp'?-1:1),1);const nextKey=dateKey(next);setView(next);setFocus(nextKey);requestAnimationFrame(()=>buttons.current.get(nextKey)?.focus())}}>{date.getDate()}</button></div>})}</div>)}</div></>}
 <div className="date-picker-shortcuts"><button type="button" onClick={()=>jump(0)}>Aujourd’hui</button><button type="button" onClick={()=>jump(1)}>Demain</button><button type="button" onClick={()=>jump(7)}>Dans 7 jours</button></div>{!required&&value&&<div className="date-picker-footer"><button type="button" onClick={()=>{onValueChange('');setOpen(false)}}>Effacer la date</button></div>}
 </Popover.Content></Popover.Portal></Popover.Root>{required&&<input className="date-validation" aria-hidden="true" tabIndex={-1} required value={selected?value:""} onChange={()=>{}} onInvalid={e=>{e.preventDefault();setInvalid(true);trigger.current?.focus()}}/>}</>;
}
